.TH CONFLICT %manext8% "%nmhdate%" MH.6.8 [%nmhversion%]
.\"
.\" %nmhwarning%
.\"
.SH NAME
conflict \- search for alias/password conflicts
.SH SYNOPSIS
.HP 5
.na
.B %libdir%/conflict
.RB [ \-search
.IR directory ]
.RB [ \-mail
.IR name ]
.RB [ \-version ]
.RB [ \-help ] 
.RI [ aliasfiles
\&...]
.ad
.SH STATUS
.B Conflict is deprecated and will be removed from the next nmh release.
.SH DESCRIPTION
.B Conflict
is a program that checks to see if the interface between
.B nmh
and the transport system is in good shape
.PP
.B Conflict
also checks for maildrops in %mailspool% which do not
belong to a valid user.  It assumes that no user name will start with
`.', and thus ignores files in %mailspool% which begin with `.'.  It also
checks for entries in the
.BR group (5)
file which do not belong
to a valid user, and for users who do not have a valid group number.
In addition duplicate users and groups are noted.
.PP
If the
.B \-mail
.I name
switch is used, then the results will be sent
to the specified
.IR name .
Otherwise, the results are sent to the standard output.
.PP
The
.B \-search
.I directory
switch can be used to search directories
other than %mailspool% and to report anomalies in those directories.
The
.B \-search
.I directory
switch can appear more than one time in an
invocation to
.BR conflict .
.PP
.B Conflict
should be run under
.IR cron (8),
or whenever system accounting takes place.
.SH FILES
.fc ^ ~
.nf
.ta \w'%etcdir%/ExtraBigFileName  'u
^%etcdir%/mts.conf~^nmh mts configuration file
^/etc/passwd~^List of users
^/etc/group~^List of groups
^%bindir%/mhmail~^Program to send mail
^%mailspool%/~^Directory of mail drop
.fi
.SH "PROFILE COMPONENTS"
None
.SH "SEE ALSO"
.IR mh\-alias (5)
.SH "DEFAULTS"
.nf
.RB ` aliasfiles "' defaults to %etcdir%/MailAliases"
.fi
.SH CONTEXT
None
