.TH FMTDUMP %manext8% "January 1, 2001" "%nmhversion%"
.\"
.\" %nmhwarning%
.\"
.SH NAME
fmtdump \- decode nmh format files
.SH SYNOPSIS
.HP 5
.na
.B %nmhlibexecdir%/fmtdump
.RB [ \-help ] 
.RB [ \-version ]
.RB [ \-form
.IR formatfile ]
.RB [ \-format
.IR string ]
.ad
.SH DESCRIPTION
.B fmtdump
is a program that parses an
.B nmh
format file and produces a pseudo-language listing of the how
.B nmh
interprets the file.  This is useful when debugging a complicated format file.
.PP
The
.B \-format
.I string
and
.B \-form
.I formatfile
switches may be
used to specify a format string or format file to read.  The string
is simply a format string and the file is simply a format file.
See
.IR mh-format (5)
for the details.
.SH FILES
.PD 0
.TP 20
$HOME/.mh_profile
The user's profile.
.TP
%nmhetcdir%/scan.default
The default format file.
.PD
.SH "PROFILE COMPONENTS"
.TP 20
Path:
To determine the user's nmh directory.
.SH "SEE ALSO"
.IR mh-format (5),
.IR mh-sequences (8)
.SH CONTEXT
None
