.\"
.\" %nmhwarning%
.\" $Id$
.\"
.\" include the -mh macro file
.so %etcdir%/tmac.h
.\"
.if '\*(ZZ'-man' \{\
.TH MH-CHART %manext1% MH.6.8 [%nmhversion%]
.SH NAME
mh-chart \- Chart of nmh Commands
.SH SYNOPSIS
.in +.5i
.ti -.5i
.\}
.in 1i
.na
.ti .5i
.ne 7
ali
\%[\-alias\ aliasfile]
\%[\-list] \%[\-nolist]
\%[\-normalize] \%[\-nonormalize]
\%[\-user] \%[\-nouser]
aliases\ ...
\%[\-version]
\%[\-help] 

.ti .5i
.ne 6
anno
\%[+folder] \%[msgs]
\%[\-component\ field]
\%[\-inplace] \%[\-noinplace]
\%[\-date] \%[\-nodate]
\%[\-text\ body]
\%[\-version]
\%[\-help]

.ti .5i
.ne 6
burst
\%[+folder] \%[msgs]
\%[\-inplace] \%[\-noinplace]
\%[\-quiet] \%[\-noquiet]
\%[\-verbose] \%[\-noverbose]
\%[\-version]
\%[\-help]

.ti .5i
.ne 9
comp
\%[+folder] \%[msg]
\%[\-draftfolder\ +folder] \%[\-draftmessage\ msg] \%[\-nodraftfolder]
\%[\-editor\ editor] \%[\-noedit]
\%[\-file\ file]
\%[\-form\ formfile]
\%[\-use] \%[\-nouse]
\%[\-whatnowproc\ program] \%[\-nowhatnowproc]
\%[\-version]
\%[\-help]

.ti .5i
.ne 9
dist
\%[+folder] \%[msg] 
\%[\-annotate] \%[\-noannotate] 
\%[\-draftfolder\ +folder] \%[\-draftmessage\ msg] \%[\-nodraftfolder]
\%[\-editor\ editor] \%[\-noedit]
\%[\-form\ formfile] 
\%[\-inplace] \%[\-noinplace] 
\%[\-whatnowproc\ program] \%[\-nowhatnowproc]
\%[\-version]
\%[\-help]

.ti .5i
.ne 9
flist
\%[+folder1 [+folder2 ...]]
\%[\-sequence\ name1 [\-sequence\ name2 ...]]
\%[\-all] \%[\-noall]
\%[\-showzero] \%[\-noshowzero]
\%[\-alpha] \%[\-noalpha]
\%[\-recurse] \%[\-norecurse]
\%[\-fast] \%[\-nofast]
\%[\-version]
\%[\-help]

.ti .5i
.ne 4
%libdir%/fmtdump
\%[\-form\ formatfile]
\%[\-format\ string]
\%[\-version]
\%[\-help]

.ti .5i
.ne 12
folder
\%[+folder] \%[msg]
\%[\-all] \%[\-noall]
\%[\-fast] \%[\-nofast]
\%[\-header] \%[\-noheader]
\%[\-pack] \%[\-nopack]
\%[\-recurse] \%[\-norecurse]
\%[\-total] \%[\-nototal]
\%[\-print] \%[\-noprint]
\%[\-list] \%[\-nolist]
\%[\-push] \%[\-pop]
\%[\-version]
\%[\-help]

.ti .5i
folders

.ti .5i
.ne 11
forw
\%[+folder] \%[msgs]
\%[\-annotate] \%[\-noannotate]
\%[\-draftfolder\ +folder] \%[\-draftmessage\ msg] \%[\-nodraftfolder]
\%[\-editor\ editor] \%[\-noedit]
\%[\-filter\ filterfile]
\%[\-form\ formfile]
\%[\-format] \%[\-noformat]
\%[\-inplace] \%[\-noinplace]
\%[\-mime] \%[\-nomime]
\%[\-whatnowproc\ program] \%[\-nowhatnowproc]
\%[\-version]
\%[\-help]

.ti .5i
.ne 5
forw
\%[+folder] \%[msgs]
\%[\-digest\ list] \%[\-issue\ number] \%[\-volume\ number]
\%[other\ switches\ for\ \fIforw\fR]
\%[\-version]
\%[\-help]

.ti .5i
.ne 11
inc
\%[+folder]
\%[\-audit\ audit\-file] \%[\-noaudit]
\%[\-changecur] \%[\-nochangecur]
\%[\-file\ name]
\%[\-form\ formatfile]
\%[\-format\ string]
\%[\-silent] \%[\-nosilent]
\%[\-truncate] \%[\-notruncate]
\%[\-width\ columns]
%nmhbeginpop%
\%[\-host\ hostname]
\%[\-user\ username]
\%[\-pack\ file]
\%[\-nopack]
%nmhendpop%
\%[\-version]
\%[\-help]

.ti .5i
.ne 7
mark
\%[+folder] \%[msgs]
\%[\-sequence\ name\ ...]
\%[\-add] \%[\-delete] \%[\-list] 
\%[\-public] \%[\-nopublic]
\%[\-zero] \%[\-nozero]
\%[\-version]
\%[\-help]

.ti .5i
.ne 9
mhbuild
file
\%[\-list] \%[-nolist]
\%[\-realsize] \%[\-norealsize]
\%[\-headers] \%[\-noheaders]
\%[\-ebcdicsafe] \%[\-noebcdicsafe]
\%[\-rfc934mode] \%[\-norfc934mode]
\%[\-verbose] \%[\-noverbose]
\%[\-check] \%[\-nocheck]
\%[\-version]
\%[\-help]

.ti .5i
.ne 9
%libdir%/mhl 
\%[\-bell] \%[\-nobell]
\%[\-clear] \%[\-noclear]
\%[\-folder\ +folder]
\%[\-form\ formfile]
\%[\-length\ lines] \%[\-width\ columns] 
\%[\-moreproc\ program] \%[\-nomoreproc]
\%[files\ ...]
\%[\-version]
\%[\-help] 

.ti .5i
.ne 8
mhmail
\%[
addrs\ ... 
\%[\-body\ text]
\%[\-cc\ addrs\ ...]
\%[\-from\ addr]
\%[\-subject subject]]
\%[\-version]
\%[\-help]

.ti .5i
.ne 16
mhn
\%[+folder] \%[msgs] \%[\-file file]
\%[\-part number]... \%[\-type content]...
\%[\-show] \%[\-noshow]
\%[\-list] \%[-nolist]
\%[\-store] \%[\-nostore]
\%[\-cache] \%[\-nocache]
\%[\-headers] \%[\-noheaders]
\%[\-realsize] \%[\-norealsize]
\%[\-serialonly] \%[\-noserialonly]
\%[\-form formfile]
\%[\-pause] \%[\-nopause]
\%[\-auto] \%[\-noauto]
\%[\-rcache policy] \%[\-wcache policy]
\%[\-check] \%[\-nocheck]
\%[\-verbose] \%[\-noverbose]
\%[\-version]
\%[\-help]

.ti .5i
.ne 5
mhparam
\%[profile-components]
\%[\-components] \%[\-nocomponents]
\%[\-all]
\%[\-version]
\%[\-help]

.ti .5i
.ne 3
mhpath
\%[+folder] \%[msgs]
\%[\-version]
\%[\-help]

.ti .5i
.ne 5
msgchk
\%[\-date] \%[\-nodate]
\%[\-notify\ all/mail/nomail] \%[\-nonotify\ all/mail/nomail]
%nmhbeginpop%
\%[\-host\ hostname]
\%[\-user\ username]
%nmhendpop%
\%[users\ ...]
\%[\-version]
\%[\-help]

.ti .5i
.ne 5
msh
\%[\-prompt\ string]
\%[\-scan] \%[\-noscan]
\%[\-topcur] \%[\-notopcur]
\%[file]
\%[\-version]
\%[\-help]

.ti .5i
.ne 6
next 
\%[+folder]
\%[\-showproc\ program]
\%[\-showmimeproc\ program]
.br
\%[\-header] \%[\-noheader]
\%[\-checkmime] \%[\-nocheckmime]
.br
\%[switches\ for\ \fIshowproc\fR or\ \fIshowmimeproc\fR]
.br
\%[\-version]
\%[\-help]

.ti .5i
.ne 5
packf
\%[+folder] \%[msgs]
\%[-file\ name]
\%[-mbox] \%[-mmdf]
\%[\-version]
\%[\-help]

.ti .5i
.ne 10
pick
\%[+folder] \%[msgs]
\%[\-and\ ...] \%[\-or\ ...] \%[\-not\ ...] \%[\-lbrace\ ...\ \-rbrace]
\%[\-\|\-component\ pattern]
\%[\-after\ date] \%[\-before\ date] \%[\-datefield\ field]
\%[\-sequence\ name\ ...]
\%[\-public] \%[\-nopublic]
\%[\-zero] \%[\-nozero]
\%[\-list] \%[\-nolist]
\%[\-version]
\%[\-help]

.ti .5i
.ne 6
prev 
\%[+folder]
\%[\-showproc\ program]
\%[\-showmimeproc\ program]
.br
\%[\-header] \%[\-noheader]
\%[\-checkmime] \%[\-nocheckmime]
.br
\%[\-switches\ for\ \fIshowproc\fR or\ \fIshowmimeproc\fR]
.br
\%[\-version]
\%[\-help]

.ti .5i
.ne 7
prompter
\%[\-erase\ chr]
\%[\-kill\ chr]
\%[\-prepend] \%[\-noprepend]
\%[\-rapid] \%[\-norapid]
\%[\-doteof] \%[\-nodoteof]
file
\%[\-version]
\%[\-help]

.ti .5i
.ne 5
%libdir%/rcvdist
\%[\-form\ formfile]
\%[switches\ for\ \fIpostproc\fR]
address1\ ...
\%[\-version]
\%[\-help]

.ti .5i
.ne 4
%libdir%/rcvpack
file
\%[-mbox] \%[-mmdf]
\%[\-version]
\%[\-help]

.ti .5i
.ne 7
%libdir%/rcvstore
\%[+folder]
\%[\-create] \%[\-nocreate]
\%[\-unseen] \%[\-nounseen]
\%[\-sequence\ name\ ...]
\%[\-public] \%[\-nopublic]
\%[\-zero] \%[\-nozero]
\%[\-version]
\%[\-help]

.ti .5i
.ne 10
%libdir%/rcvtty
\%[command]
\%[\-form\ formatfile]
\%[\-format\ string]
\%[\-width\ columns]
\%[\-bell] \%[\-nobell]
\%[\-newline]
\%[\-nonewline]
\%[\-biff]
\%[\-version]
\%[\-help]

.ti .5i
.ne 9
refile 
\%[msgs] 
\%[\-draft]
\%[\-link] \%[\-nolink] 
\%[\-preserve] \%[\-nopreserve]
\%[\-unlink] \%[\-nounlink]
\%[\-src\ +folder] 
\%[\-file\ file] 
+folder ...
\%[\-version]
\%[\-help]

.ti .5i
.ne 15
repl
\%[+folder] \%[msg]
\%[\-group] \%[\-nogroup]
\%[\-annotate] \%[\-noannotate]
\%[\-cc\ all/to/cc/me] \%[\-nocc\ all/to/cc/me]
\%[\-draftfolder\ +folder] \%[\-draftmessage\ msg] \%[\-nodraftfolder]
\%[\-editor\ editor] \%[\-noedit]
\%[\-fcc\ +folder]
\%[\-filter\ filterfile]
\%[\-form\ formfile]
\%[\-format] \%[\-noformat]
\%[\-inplace] \%[\-noinplace]
\%[\-query] \%[\-noquery]
\%[\-whatnowproc\ program] \%[\-nowhatnowproc]
\%[\-width\ columns]
\%[\-version]
\%[\-help]

.ti .5i
.ne 4
rmf 
\%[+folder]
\%[\-interactive] \%[\-nointeractive]
\%[\-version]
\%[\-help]

.ti .5i
.ne 3
rmm
\%[+folder] \%[msgs]
\%[\-unlink] \%[\-nounlink]
\%[\-version]
\%[\-help]

.ti .5i
.ne 8
scan
\%[+folder] \%[msgs]
\%[\-clear] \%[\-noclear]
\%[\-form\ formatfile]
\%[\-format\ string]
\%[\-header] \%[\-noheader]
\%[\-width\ columns]
\%[\-reverse] \%[\-noreverse]
\%[\-file filename]
\%[\-version]
\%[\-help]

.ti .5i
.ne 15
send
\%[\-alias\ aliasfile]
\%[\-draft] 
\%[\-draftfolder\ +folder] \%[\-draftmessage\ msg] \%[\-nodraftfolder]
\%[\-filter\ filterfile] \%[\-nofilter]
\%[\-format] \%[\-noformat]
\%[\-forward] \%[\-noforward]
\%[\-mime] \%[\-nomime]
\%[\-msgid] \%[\-nomsgid]
\%[\-push] \%[\-nopush]
\%[\-split\ seconds]
\%[\-verbose] \%[\-noverbose]
\%[\-watch] \%[\-nowatch]
\%[\-width\ columns]
\%[file\ ...] 
\%[\-version]
\%[\-help]

.ti .5i
.ne 7
show
\%[+folder] \%[msgs]
\%[\-showproc\ program]
.br
\%[\-showmimeproc\ program]
\%[\-header] \%[\-noheader]
.br
\%[\-draft]
\%[\-checkmime] \%[\-nocheckmime]
.br
\%[switches\ for\ \fIshowproc\fR or \fIshowmimeproc\fR]
.br
\%[\-version]
\%[\-help]

.ti .5i
.ne 5
sortm
\%[+folder] \%[msgs]
\%[\-datefield\ field]
\%[\-textfield\ field] \%[\-notextfield]
\%[\-limit days] \%[\-nolimit]
\%[\-verbose] \%[\-noverbose]
\%[\-version]
\%[\-help]

.ti .5i
.ne 6
whatnow
\%[\-draftfolder\ +folder] \%[\-draftmessage\ msg] \%[\-nodraftfolder]
\%[\-editor\ editor] \%[\-noedit]
\%[\-prompt\ string]
\%[file]
\%[\-version]
\%[\-help]

.ti .5i
.ne 7
whom
\%[\-alias\ aliasfile]
\%[\-check] \%[\-nocheck]
\%[\-draft]
\%[\-draftfolder\ +folder] \%[\-draftmessage\ msg] \%[\-nodraftfolder]
\%[file]
\%[\-version]
\%[\-help]

.ti .5i
.ne 7
%libdir%/ap
\%[\-form\ formatfile]
\%[\-format\ string]
\%[\-normalize] \%[\-nonormalize]
\%[\-width\ columns]
addrs\ ...
\%[\-version]
\%[\-help] 

.ti .5i
.ne 5
%libdir%/conflict
\%[\-mail\ name]
\%[\-search\ directory]
\%[aliasfiles\ ...]
\%[\-version]
\%[\-help]

.ti .5i
.ne 5
%libdir%/dp
\%[\-form\ formatfile]
\%[\-format\ string]
\%[\-width\ columns]
dates\ ...
\%[\-version]
\%[\-help]

.ti .5i
.ne 3
%libdir%/install\-mh
\%[\-auto]

.ti .5i
.ne 11
%libdir%/post 
\%[\-alias\ aliasfile]
\%[\-filter\ filterfile] \%[\-nofilter]
\%[\-format] \%[\-noformat]
\%[\-mime] \%[\-nomime]
\%[\-msgid] \%[\-nomsgid]
\%[\-verbose] \%[\-noverbose]
\%[\-watch] \%[\-nowatch]
\%[\-width\ columns]
file
\%[\-version]
\%[\-help]

.ti .5i
.ne 10
%libdir%/slocal \%[address\ info\ sender]
.br
\%[\-addr\ address]
\%[\-info\ data]
\%[\-sender\ sender]
.br
\%[\-user\ username]
\%[\-mailbox\ mbox]
\%[\-file\ file]
.br
\%[\-maildelivery\ deliveryfile]
\%[\-suppressdup]
.br
\%[\-nosuppressdup]
\%[\-verbose] \%[\-noverbose]
\%[\-debug]
.br
\%[\-version]
\%[\-help]
.ad
.in 0
