.\"
.\" %nmhwarning%
.\"
.TH MHN %manext1% "%nmhdate%" MH.6.8 [%nmhversion%]
.SH NAME
mhn \- display/list/store/cache MIME messages
.SH SYNOPSIS
.HP 5
.na
.B mhn
.RI [ +folder ]
.RI [ msgs ]
.RB [ \-file
.IR file ]
.RB [ \-part
.IR number ]
\&...
.RB [ \-type
.IR content ]
\&...
.RB [ \-show " | " \-noshow ]
.RB [ \-list " | " \-nolist ]
.RB [ \-store " | " \-nostore ]
.RB [ \-cache " | " \-nocache ]
.RB [ \-headers " | " \-noheaders ]
.RB [ \-realsize " | " \-norealsize ]
.RB [ \-serialonly " | " \-noserialonly ]
.RB [ \-form
.IR formfile ]
.RB [ \-pause " | " \-nopause ]
.RB [ \-auto " | " \-noauto ]
.RB [ \-rcache
.IR policy ]
.RB [ \-wcache
.IR policy ]
.RB [ \-check " | " \-nocheck ]
.RB [ \-version ]
.RB [ \-help ]
.PP
.HP 5
.B mhn
.B \-build
.I file
.RB [ \-ebcdicsafe " | " \-noebcdicsafe ]
.RB [ \-rfc934mode " | " \-norfc934mode ]
.ad
.SH DESCRIPTION
.B MHN SHOULD BE CONSIDERED DEPRECATED.  IT IS RETAINED FOR THE PURPOSE
.B OF BACKWARD COMPATIBILITY, BUT EVERYONE SHOULD MIGRATE TO USING THE
.B COMMANDS MHSHOW, MHSTORE, AND MHLIST.  CHECK THE INDIVIDUAL MAN PAGES
.B FOR DETAILS.

.SH "SEE ALSO"
mhbuild(1), mhl(1), sendfiles(1)
