.TH RCVDIST %manext1% 1999-04-30 "%nmhversion%"
.
.\" %nmhwarning%
.
.SH NAME
rcvdist \- asynchronously receive and distribute new email
.SH SYNOPSIS
.HP 5
.na
.B %nmhlibexecdir%/rcvdist
.RB [ \-help ]
.RB [ \-version ]
.RB [ \-form
.IR formfile ]
[switches\ for
.IR postproc ]
.I address1
\&...
.ad
.SH DESCRIPTION
.B rcvdist
accepts a message on its standard input and resends a copy of
the message to all of the addresses listed on its command line.
.PP
The format of the Resent-xxx header fields is specified by the form file
.RI \*(lq rcvdistcomps \*(rq.
If a file named
.RI \*(lq rcvdistcomps \*(rq
exists in the user's nmh directory, it will be used instead of the
default file.
You may specify an alternate forms file with
.B \-form
.IR formfile .
.PP
The
.RI \*(lq rcvdistcomps \*(rq
file uses the format string facility described in
.IR mh\-format (5).
In addition to the standard format escapes,
.B rcvdist
also recognizes the following
.I component
escape:
.PP
.RS 5
.nf
.ta \w'Dtimenow  'u +\w'Returns  'u
.I "Escape	Returns	Description"
addresses	string	the addresses to distribute to
.fi
.RE
.PP
By default,
.B rcvdist
uses the
.B post
program to deliver the message, although this can be changed by
defining the
.I postproc
profile component.
.SH FILES
.fc ^ ~
.nf
.ta \w'%nmhetcdir%/ExtraBigFileName  'u
^%nmhetcdir%/rcvdistcomps~^Default message skeleton
^or <mh-dir>/rcvdistcomps~^User's message skeleton
^%nmhetcdir%/mts.conf~^nmh mts configuration file
^%nmhetcdir%/maildelivery~^Default delivery file
^$HOME/.maildelivery~^User's delivery file
.fi
.SH "SEE ALSO"
.IR rcvpack (1),
.IR rcvstore (1),
.IR rcvtty (1),
.IR slocal (1),
.IR mh\-format (5)
