.TH RCVDIST %manext1% "January 18, 2001" "%nmhversion%"
.\"
.\" %nmhwarning%
.\"
.SH NAME
rcvdist \- asynchronously redistribute new mail
.SH SYNOPSIS
.HP 5
.na
.B %nmhlibexecdir%/rcvdist
.RB [ \-help ]
.RB [ \-version ]
.RB [ \-form
.IR formfile ]
[switches\ for
.IR postproc ]
.I address1
\&...
.ad
.SH DESCRIPTION
The
.B rcvdist
program will accept a message on its standard input
and resend a copy of this message to all of the addresses listed on its
command line.
.PP
When a message is redistributed with the
.B rcvdist
command, the
format of the Resent-xxx header fields is controlled by the forms files
.RI \*(lq rcvdistcomps \*(rq.
If a file named
.RI \*(lq rcvdistcomps \*(rq
exists in the user's nmh
directory, it will be used instead of the default one.  You may specify
an alternate forms file with the switch
.B \-form
.IR formfile .
.PP
The
.RI \*(lq rcvdistcomps \*(rq
file uses the format string facility described in
.IR mh\-format (5).
In addition to the standard format escapes,
.B rcvdist
also recognizes the following additional
.I component
escape:
.PP
.RS 5
.nf
.ta \w'Dtimenow  'u +\w'Returns  'u
.I "Escape	Returns	Description"
addresses	string	the addresses to distribute to
.fi
.RE
.PP
By default,
.B rcvdist
uses the program
.B post
to do the actual
delivery of the message, although this can be changed by defining the
.I postproc
profile component.
.SH FILES
.fc ^ ~
.nf
.ta \w'%nmhetcdir%/ExtraBigFileName  'u
^%nmhetcdir%/rcvdistcomps~^Default message skeleton
^or <mh\-dir>/rcvdistcomps~^Rather than standard message skeleton
^%nmhetcdir%/mts.conf~^nmh mts configuration file
^$HOME/\&.maildelivery~^The file controlling local delivery
^%nmhetcdir%/maildelivery~^Rather than the standard file
.fi
.SH "SEE ALSO"
.IR rcvpack (1),
.IR rcvstore (1),
.IR rcvtty (1), 
.IR slocal (1),
.IR mh\-format (5)
