.TH RCVPACK %manext1% 1999-04-30 "%nmhversion%"
.
.\" %nmhwarning%
.
.SH NAME
rcvpack \- append an email from standard input to a file
.SH SYNOPSIS
.HP 5
.na
.B %nmhlibexecdir%/rcvpack
.RB [ \-help ]
.RB [ \-version ]
.I file
.RB [ \-mbox ]
.RB [ \-mmdf ]
.ad
.SH DESCRIPTION
.B rcvpack
appends a copy of a message to the file specified
on its command line.
.PP
If the
.B \-mbox
switch is given (the default), messages are separated by
mbox (uucp) style delimiters.  This is the format used
by most mail clients (elm, mailx, etc.).
.PP
Alternatively, if the
.B \-mmdf
switch is given, messages are separated by mmdf style
delimiters, each message being separated by four
CTRL\-A's and a newline.
.PP
.B rcvpack
will correctly lock and unlock the file to serialize
access when running multiple copies of
.BR rcvpack .
.PP
In general,
.B rcvpack
has been rendered obsolete by the
.B file
action of
.BR slocal ,
although it may still have some use in shell scripts.
.SH FILES
.fc ^ ~
.nf
.ta \w'%nmhetcdir%/ExtraBigFileName  'u
^%nmhetcdir%/mts.conf~^nmh mts configuration file
.fi
.SH "SEE ALSO"
.IR rcvdist (1),
.IR rcvstore (1),
.IR rcvtty (1),
.IR slocal (1)
.SH BUGS
Only two return codes are meaningful, others should be.
