.\"
.\" %nmhwarning%
.\"
.TH RCVPACK %manext1% "%nmhdate%" MH.6.8 [%nmhversion%]
.SH NAME
rcvpack \- append message to file
.SH SYNOPSIS
.HP 5
.na
.B %libdir%/rcvpack
.I file
.RB [ \-mbox ]
.RB [ \-mmdf ]
.RB [ \-version ]
.RB [ \-help ]
.ad
.SH DESCRIPTION
The
.B rcvpack
program will append a copy of the message to the file
listed on its command line.
.PP
If the
.B \-mbox
switch is given (the default), then the messages are
separated using mbox (uucp) style delimiters.  This is the format used
by most mail clients (elm, mailx, etc.).
.PP 
If the
.B \-mmdf
switch is given, then the messages are separated by
mmdf style delimiters.  Each message in the file is separated by four
CTRL\-A's and a newline.
.PP
.B rcvpack
will correctly lock and unlock the file to serialize
access to the file, when running multiple copies of
.B rcvpack .
.PP
In general, its use is obsoleted by the
.B file
action of
.BR slocal ,
although it might still have occasional uses in various
shell scripts.

.SH FILES
.fc ^ ~
.nf
.ta \w'%etcdir%/ExtraBigFileName  'u
^%etcdir%/mts.conf~^nmh mts configuration file
.fi

.SH "SEE ALSO"
rcvdist(1), rcvstore(1), rcvtty(1), slocal(1)

.SH BUGS
Only two return codes are meaningful, others should be.
