#!/bin/sh
#
# This exists so "make check" will always clean up the "inst" directory
# after a run, even if tests fail.  That way if you fix a problem and do
# another "make check", you will get new binaries to test against.
# 

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname $0`/..
    MH_OBJ_DIR=`cd $srcdir && pwd`; export MH_OBJ_DIR
fi

. "${MH_OBJ_DIR}/test/common.sh"

rm -rf "${MH_TEST_DIR}"/.w3m

rm -rf "${MH_INST_DIR}"
