#!/bin/sh

export MH=`cat test-temp-dir`/mh_profile
export MH_TEST_DIR=`cat test-temp-dir`
export PATH=$MH_TEST_DIR/bin:$PATH

/bin/sh $1

return_value=$?

if [ $return_value -eq 0 ] ; then
    echo Test $1 PASS
else
    echo Test $1 FAIL
fi
