#!/bin/sh

status=1

[ $# -eq 1 ]  ||  echo "usage: $0 "'<testname>'

# Get full pathnames that we'll need.
cd `dirname $0`

export MH_TEST_DIR=`pwd`/testinstall
export MH=$MH_TEST_DIR/Mail/.mh_profile
export PATH=$MH_TEST_DIR/bin:$PATH
export MH_TEST_COMMON=$PWD/common.sh

[ -d $MH_TEST_DIR ] || ./setup-test

# clean old test data
trap "rm -rf $MH_TEST_DIR/Mail; exit \$status" 0
# setup test data
rm -rf $MH_TEST_DIR/Mail
mkdir $MH_TEST_DIR/Mail
echo "Path: $MH_TEST_DIR/Mail" > $MH
folder -create +inbox > /dev/null
# create 10 basic messages
for i in 1 2 3 4 5 6 7 8 9 10;
do
    cat > $MH_TEST_DIR/Mail/inbox/$i <<EOF
From: Test$i <test$i@example.com>
To: Some User <user@example.com>
Date: Fri, 29 Sep 2006 00:00:00
Subject: Testing message $i

This is message number $i
EOF
done

# now run the test
set +e
/bin/sh $1
return_value=$?
set -e

if [ $return_value -eq 0 ]; then
    echo Test $1 PASS
    status=0
elif [ $return_value -eq 120 ]; then
    # indicates test was skipped (eg needed program not found)
    # test itself should have printed a message about this,
    # so print nothing here.
    status=0
else
    echo Test $1 FAIL
fi
