#!/bin/sh
######################################################
#
# Test that errors are not written to stdout.
#
######################################################

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname "$0"`/../..
    MH_OBJ_DIR=`cd "$srcdir" && pwd`; export MH_OBJ_DIR
fi

. "$MH_OBJ_DIR/test/common.sh"

setup_test

expected_err=$MH_TEST_DIR/$$.expected_err
expected_out=$MH_TEST_DIR/$$.expected_out
actual_err=$MH_TEST_DIR/$$.actual_err
actual_out=$MH_TEST_DIR/$$.actual_out

# Error message should go to stderr.
cat > $expected_err <<EOF
pick: -a ambiguous.  It matches
  -and
  -after date
EOF
# Nothing should to go stdout.
cat /dev/null > $expected_out

run_prog pick -a > $actual_out 2> $actual_err  ||  true
check "$expected_err" "$actual_err"
check "$expected_out" "$actual_out"
