/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: flex.skel,v 1.2 90/06/27 22:56:49 leres Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>

#ifdef __STDC__

#ifndef DONT_HAVE_STDLIB_H
#include <stdlib.h>
#else
void *malloc( unsigned );
void free( void* );
#endif

#define YY_USE_PROTOS
#define YY_USE_CONST
#endif


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#ifndef __STDC__
#include <stdlib.h>
#endif

#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#endif


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* there's no standard place to get these definitions */
char *malloc();
int free();
int read();
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR char
#define INITIAL 0
#ifndef lint
static char rcsid[] =
#ifdef FLEX_SCANNER
    "@(#) $Header: dtimep.lex,v 1.15 90/10/16 14:57:20 leres Locked $ (LBL) (flex generated scanner)";
#else
    "@(#) $Header: dtimep.lex,v 1.15 90/10/16 14:57:20 leres Locked $ (LBL) (lex generated scanner)";
#endif
#endif
/*
%e 2000
%p 5000
%n 1000
%a 4000
 */
#define Z 1
#include "tws.h"
#include <ctype.h>

/*
 * Patchable flag that says how to interpret NN/NN/NN dates. When
 * true, we do it European style: DD/MM/YY. When false, we do it
 * American style: MM/DD/YY.
 */
int europeandate = 0;

/*
 * Table to convert month names to numeric month.  We use the
 * fact that the low order 5 bits of the sum of the 2nd & 3rd
 * characters of the name is a hash with no collisions for the 12
 * valid month names.  (The mask to 5 bits maps any combination of
 * upper and lower case into the same hash value).
 */
static	int month_map[] = {
	0,
	6,	/* 1 - Jul */
	3,	/* 2 - Apr */
	5,	/* 3 - Jun */
	0,
	10,	/* 5 - Nov */
	0,
	1,	/* 7 - Feb */
	11,	/* 8 - Dec */
	0,
	0,
	0,
	0,
	0,
	0,
	0,	/*15 - Jan */
	0,
	0,
	0,
	2,	/*19 - Mar */
	0,
	8,	/*21 - Sep */
	0,
	9,	/*23 - Oct */
	0,
	0,
	4,	/*26 - May */
	0,
	7	/*28 - Aug */
};
/*
 * Same trick for day-of-week using the hash function
 *  (c1 & 7) + (c2 & 4)
 */
static	int day_map[] = {
	0,
	0,
	0,
	6,	/* 3 - Sat */
	4,	/* 4 - Thu */
	0,
	5,	/* 6 - Fri */
	0,	/* 7 - Sun */
	2,	/* 8 - Tue */
	1	/* 9 - Mon */,
	0,
	3	/*11 - Wed */
};
#define SETDAY	{ tw.tw_wday= day_map[(cp[0] & 7) + (cp[1] & 4)];\
		tw.tw_flags &= ~TW_SDAY; tw.tw_flags |= TW_SEXP;\
		cp += 2; }
#define SETMONTH { tw.tw_mon = month_map[(cp[0] + cp[1]) & 0x1f]; gotdate++;\
		 cp += 2;\
		 SKIPD;}
#define CVT2	(i=(*cp++ - '0'),isdigit(*cp)? i*10 + (*cp++ - '0') : i)
#define SKIPD	{ while ( !isdigit(*cp++) ) ;  --cp; }
#define EXPZONE	{ tw.tw_flags &= ~TW_SZONE; tw.tw_flags |= TW_SZEXP; }
#define ZONE(x)	{ tw.tw_zone=(x); EXPZONE; }
#define ZONED(x) { ZONE(x); tw.tw_flags |= TW_DST; }
#define	LC(c)	(isupper(c) ? tolower(c) : (c))

#ifdef FLEX_SCANNER
/* We get passed a string and return a pointer to a static tws struct */
#undef YY_DECL
#define YY_DECL struct tws *dparsetime(str) char *str;

/* We assume that we're never passed more than max_size characters */
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if (gstr) { \
		register char *xp; \
		xp = gstr; \
		while (isspace(*xp)) \
			xp++; \
		gstr = xp; \
		while (*xp != '\0') \
			++xp; \
		result = xp - gstr; \
		bcopy(gstr, buf, result); \
		gstr = 0; \
	} else \
		result = YY_NULL;

/* Date strings aren't usually very long */
#undef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 128

/* Use mh error reporting routine */
#undef YY_FATAL_ERROR
#define YY_FATAL_ERROR(s) adios("dparsetime()", s);

/* We need a pointer to the matched text we can modify */
#undef YY_USER_ACTION
#define YY_USER_ACTION cp = yytext

/* Used to initialize */
static struct tws ztw = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

/* Global for use by YY_INPUT() macro */
static char *gstr;
#endif


/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters*/
    int yy_buf_size;	

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 44
typedef int yy_state_type;
static const short int yy_accept[390] =
    {   0,
        0,    0,    0,    0,   44,   42,   40,   39,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   42,   35,   35,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   40,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   14,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    8,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    1,    0,    0,    0,    0,    0,    1,
        0,    0,    1,    0,    1,    1,    1,    1,    0,    0,
       28,   27,   33,   21,   20,   19,   18,   15,   32,   31,
       17,   16,   23,   22,   26,   25,   24,   30,   29,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   13,    8,
        8,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   12,    0,    0,    0,
        0,    0,    1,    1,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        2,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       13,    0,    7,    9,   10,    0,    0,    4,    4,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       12,    6,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   37,   38,
        2,    0,    0,    0,    0,    0,    0,    0,    3,    3,
       11,    7,    7,    9,   10,    0,    4,    4,    4,    0,

        4,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        6,    0,    6,    0,    0,    0,    1,    0,    1,    0,
        0,    0,    0,    1,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    3,   11,    4,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    1,    0,    0,    0,    0,    0,    4,
        0,    0,    0,    0,    0,    5,    5,    0,    0,    0,
        1,    0,    1,    0,    0,    0,    0,    0,    0,    0,
        0,    5,    5,    5,    0,    1,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        5,    1,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   13,   13,   14,   14,   14,   15,   16,    1,    1,
        1,    1,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   33,   40,    1,
        1,    1,    1,    1,    1,    1,   17,   18,   19,   20,

       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   33,
       40,    1,    1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[41] =
    {   0,
        1,    2,    1,    1,    1,    1,    3,    1,    4,    5,
        5,    5,    5,    5,    5,    6,    7,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const short int yy_base[413] =
    {   0,
        0,    0,   40,    0,  637,  638,  634,  638,   59,   97,
      620,   72,   59,  613,   68,   83,   73,  602,  613,  101,
       79,  610,   82,  129,  125,  595,   95,  608,  101,  103,
      599,  109,  638,  114,  638,  147,   66,  608,  121,  638,
      151,  139,  590,  604,  145,  622,  589,  591,  137,  146,
      600,  187,  169,    0,  186,    0,  147,  599,  598,  156,
      601,  586,  597,  594,  128,  176,  580,  590,  593,  593,
      585,  579,  105,  141,  578,  569,  570,  569,  572,  573,
      565,  580,  580,    0,    0,  167,  564,  170,  171,  569,
      188,  190,  191,  562,  192,  560,  194,  559,  558,  557,

      556,  555,  554,  553,  552,  551,  550,  549,  548,  547,
      546,  545,  544,  543,  638,  542,  541,  551,  545,  538,
      543,  535,  550,  550,    0,  560,    0,  217,  534,  544,
      547,  547,  534,  200,  181,  525,  526,  529,    0,  218,
      201,  229,  222,  233,  230,  234,  237,  235,  558,  239,
      240,  242,  245,  243,  255,  253,  261,  262,    0,    0,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  246,
      260,  265,  266,  243,  271,  267,  548,  549,  555,  276,
      282,    0,  527,  526,  313,  258,  260,  266,  517,  264,

      532,  269,  531,  530,  282,  273,  548,  547,  520,  512,
      517,  508,  542,  541,  525,  524,  538,  537,  514,  520,
      507,  517,  500,  512,  515,  496,  510,  508,    0,    0,
      521,  510,  509,  491,  507,  488,  502,  500,    0,  505,
      517,    0,  516,  515,  514,  494,  308,  305,  328,  486,
      478,  483,  474,  493,  488,  487,  483,  477,  487,  483,
      501,  329,  500,  465,  482,  482,  458,  463,  494,  455,
      476,  472,  472,  462,  450,  469,  471,  452,  638,  638,
      638,  446,  445,  464,  443,  462,  464,  445,  477,  476,
      475,  474,  473,  472,  471,    0,  330,  470,  332,  435,

      339,  449,  433,  450,  450,  432,  444,  446,  442,  433,
      459,  458,  346,  457,  437,  423,  350,  416,  352,  434,
      420,  436,  434,  353,  434,  410,  429,  443,  442,  429,
      440,  427,  403,  422,  439,  438,  437,  436,  416,  415,
      401,  394,  412,  398,  413,  309,  396,  389,  394,  425,
      386,  404,  384,  356,  406,  382,  381,  415,  402,  416,
      383,  376,  381,  393,  392,  410,  303,  409,  408,  407,
      359,  374,  360,  366,  400,  397,  361,  377,  373,  371,
      354,  385,  382,  381,  378,  362,  374,  353,  638,  368,
      363,  360,  346,  366,  339,  370,  337,  335,  328,  314,

      376,  312,  380,  284,  189,  181,  120,  384,  388,  394,
      398,  402
    } ;

static const short int yy_def[413] =
    {   0,
      389,    1,  389,    3,  389,  389,  389,  389,  389,  389,
       10,   10,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,   52,  390,   10,  391,  389,  389,  389,  389,
      389,  389,  389,  389,   55,   52,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  392,  393,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,

      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,   53,  394,  395,  396,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  397,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  398,  399,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  400,  389,  401,  389,
      389,  402,  389,  389,  389,  195,  195,  195,  196,  196,

      197,  197,  197,  197,  197,  197,  401,  403,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  404,  405,
      389,  389,  389,  389,  389,  389,  389,  389,  406,  406,
      389,  407,  408,  389,  389,  197,  197,  409,  409,  389,
      389,  389,  389,  389,  197,  197,  389,  389,  389,  389,
      389,  410,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  400,
      389,  389,  389,  389,  389,  247,  389,  389,  389,  389,

      247,  197,  389,  389,  389,  389,  197,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  197,  389,
      389,  389,  389,  389,  389,  411,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  197,  389,  412,  412,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  197,  197,  197,
      389,  389,  389,  411,  389,  389,  389,  197,    0,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,

      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389
    } ;

static const short int yy_nxt[679] =
    {   0,
        6,    7,    8,    9,    6,    6,    6,    6,    6,   10,
       11,   10,   12,   12,   12,    6,   13,    6,    6,   14,
        6,   15,    6,    6,    6,   16,    6,    6,   17,   18,
       19,    6,    6,    6,   20,   21,    6,    6,   22,    6,
        6,    7,    8,    9,    6,   23,    6,   24,    6,   10,
       11,   10,   12,   12,   12,    6,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   35,   36,   37,
       38,   39,   40,   40,   41,   42,   43,   40,   44,   45,
       47,   66,   66,   66,   66,   66,   66,   48,   70,   74,
       67,   84,   84,   49,   50,   68,   76,   51,   52,   72,

      112,   71,   81,   75,   53,   54,   55,   55,   55,   55,
       55,   55,   56,   57,  101,   82,   58,   78,   59,   73,
      103,   79,   60,   70,  291,   61,   62,   63,  106,  102,
       72,   64,  146,  108,  147,  104,   71,   80,   85,   85,
      113,  139,  139,  107,   98,   86,   87,   88,  109,   89,
       73,   90,   91,  120,   92,  114,   67,   93,   94,   99,
       95,   68,   81,   74,  116,   96,  110,   78,   97,  122,
      125,   79,  133,  121,  148,   82,  389,   75,  129,  117,
      149,  111,  123,  130,   54,  289,   98,   80,   52,  101,
      103,   56,  134,  280,   53,  127,  127,  127,  127,  127,

      127,   99,  208,   57,  102,  104,   58,  106,   59,  108,
      110,  113,   60,  116,  202,   61,   62,   63,  190,  208,
      203,   64,  107,  208,  109,  111,  114,  200,  117,  201,
      208,  208,  192,  193,  213,  208,  208,  210,  208,  214,
      213,  208,  209,  208,  208,  214,  213,  231,  194,  211,
      231,  214,  215,  219,  213,  212,  213,  218,  220,  214,
      221,  214,  213,  213,  231,  232,  216,  214,  214,  231,
      231,  231,  222,  217,  225,  231,  236,  190,  224,  233,
      252,  223,  389,  190,  389,  235,  226,  257,  279,  389,
      389,  228,  193,  389,  251,  227,  238,  192,  193,  253,

      389,  234,  389,  255,  382,  237,  297,  194,  260,  296,
      346,  298,  259,  194,  246,  389,  243,  384,  239,  367,
      247,  300,  248,  249,  248,  248,  248,  248,  389,  297,
      311,  297,  230,  297,  298,  312,  298,  250,  298,  229,
      297,  207,  301,  189,  300,  298,  300,  311,  300,  248,
      160,  213,  312,  213,  213,  300,  214,  213,  214,  214,
      213,  213,  214,  213,  159,  214,  214,  128,  214,  188,
      188,  191,  126,  389,  191,  191,  191,  242,  231,  208,
      242,  262,  382,  382,  262,  293,  382,  388,  293,  299,
      299,  389,  299,  389,  299,  313,  313,  389,  313,  366,

      387,  231,  366,  383,  231,  386,  383,  385,  208,  208,
      208,  382,  381,  389,  380,  379,  378,  360,  377,  231,
      376,  375,  374,  373,  372,  371,  208,  370,  369,  368,
      365,  364,  363,  203,  362,  361,  389,  360,  337,  336,
      335,  359,  358,  357,  231,  356,  231,  231,  355,  354,
      353,  352,  351,  350,  349,  149,  348,  347,  208,  346,
      311,  345,  344,  343,  389,  342,  341,  340,  339,  389,
      338,  337,  295,  294,  292,  292,  336,  335,  335,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  208,  318,  317,  316,  315,

      314,  208,  261,  310,  309,  308,  307,  389,  389,  306,
      305,  304,  303,  302,  389,  295,  294,  292,  241,  290,
      288,  287,  286,  285,  284,  283,  282,  281,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  269,  208,  208,
      268,  267,  213,  213,  266,  265,  264,  263,  208,  261,
      258,  389,  256,  254,  245,  244,  241,  187,  240,  208,
      206,  205,  204,  199,  198,  197,  196,  195,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  115,  112,  105,  100,  158,

      157,  156,  155,  154,  153,  152,  151,  150,  145,  144,
      143,  142,  141,  140,  138,  137,  136,  135,  132,  131,
      124,  119,  118,   46,   83,  115,   77,  105,   69,  100,
       83,   77,   76,   69,   65,   46,  389,    5,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389
    } ;

static const short int yy_chk[679] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        9,   12,   12,   12,   12,   12,   12,    9,   15,   17,
       13,   23,   23,    9,    9,   13,   37,    9,   10,   16,

       37,   15,   21,   17,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   27,   21,   10,   20,   10,   16,
       29,   20,   10,   30,  407,   10,   10,   10,   32,   27,
       34,   10,   73,   34,   73,   29,   30,   20,   24,   24,
       39,   65,   65,   32,   25,   24,   24,   24,   34,   24,
       34,   24,   24,   49,   24,   39,   25,   24,   24,   25,
       24,   25,   42,   36,   45,   24,   36,   41,   24,   50,
       53,   41,   60,   49,   74,   42,   53,   36,   57,   45,
       74,   36,   50,   57,   66,  406,   86,   41,   52,   88,
       89,   66,   60,  405,   52,   55,   55,   55,   55,   55,

       55,   86,  141,   52,   88,   89,   52,   91,   52,   92,
       93,   95,   52,   97,  135,   52,   52,   52,  128,  140,
      135,   52,   91,  143,   92,   93,   95,  134,   97,  134,
      142,  145,  128,  128,  144,  146,  148,  141,  147,  144,
      150,  151,  140,  152,  154,  150,  153,  184,  128,  142,
      180,  153,  144,  148,  156,  143,  155,  147,  150,  156,
      151,  155,  157,  158,  181,  180,  145,  157,  158,  182,
      183,  186,  152,  146,  155,  185,  184,  190,  154,  181,
      197,  153,  196,  191,  197,  183,  156,  202,  404,  202,
      198,  158,  190,  206,  196,  157,  186,  191,  191,  198,

      200,  182,  205,  200,  367,  185,  248,  190,  206,  247,
      346,  248,  205,  191,  195,  247,  402,  367,  400,  346,
      195,  248,  195,  195,  195,  195,  195,  195,  247,  249,
      262,  297,  399,  299,  249,  262,  297,  195,  299,  398,
      301,  397,  249,  395,  249,  301,  297,  313,  299,  301,
      393,  317,  313,  319,  324,  301,  317,  354,  319,  324,
      371,  373,  354,  386,  392,  371,  373,  391,  386,  394,
      394,  396,  390,  388,  396,  396,  396,  401,  387,  385,
      401,  403,  384,  383,  403,  408,  382,  381,  408,  409,
      409,  380,  409,  379,  409,  410,  410,  378,  410,  411,

      377,  376,  411,  412,  375,  374,  412,  372,  370,  369,
      368,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  353,  352,  351,  350,  349,  348,  347,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,
      325,  323,  322,  321,  320,  318,  316,  315,  314,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      300,  298,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,

      264,  263,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  246,  245,  244,  243,  241,  240,
      238,  237,  236,  235,  234,  233,  232,  231,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      204,  203,  201,  199,  194,  193,  189,  188,  187,  149,
      138,  137,  136,  133,  132,  131,  130,  129,  126,  124,
      123,  122,  121,  120,  119,  118,  117,  116,  114,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   96,   94,   90,   87,   83,

       82,   81,   80,   79,   78,   77,   76,   75,   72,   71,
       70,   69,   68,   67,   64,   63,   62,   61,   59,   58,
       51,   48,   47,   46,   44,   43,   38,   31,   28,   26,
       22,   19,   18,   14,   11,    7,    5,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;


					register int i, gotdate;
					register char *cp;
					static struct tws tw;
					static void zonehack();

					BEGIN(INITIAL);
					yy_init = 1;
					tw = ztw;
					gstr = str;
					gotdate = 0;


    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 390 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 389 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
SETDAY;
	YY_BREAK
case 2:
{
					cp++;
					SETDAY;
					}
	YY_BREAK
case 3:
{
					if (europeandate) {
						/* European: DD/MM/YY */
						tw.tw_mday = CVT2;
						cp++;
						tw.tw_mon  = CVT2 - 1;
					} else {
						/* American: MM/DD/YY */
						tw.tw_mon  = CVT2 - 1;
						cp++;
						tw.tw_mday = CVT2;
					}
					cp++;
					for (i = 0; isdigit(*cp); )
						i = i*10 + (*cp++ - '0');
					tw.tw_year = i % 100;
					gotdate++;
					}
	YY_BREAK
case 4:
{
					tw.tw_mday = CVT2;
					while (!isalpha(*cp++))
						;
					SETMONTH;
					for (i = 0; isdigit(*cp); )
						i = i*10 + (*cp++ - '0');
					tw.tw_year = i % 100;
					}
	YY_BREAK
case 5:
{
					cp++;
					SETMONTH;
					tw.tw_mday = CVT2;
					SKIPD;
					for (i = 0; isdigit(*cp); )
						i = i*10 + (*cp++ - '0');
					tw.tw_year = i % 100;
					}
	YY_BREAK
case 6:
{
					cp++;
					SETMONTH;
					tw.tw_mday = CVT2;
					}
	YY_BREAK
case 7:
{
					tw.tw_hour = CVT2; cp++;
					tw.tw_min  = CVT2; cp++;
					tw.tw_sec  = CVT2;
					BEGIN Z;
					}
	YY_BREAK
case 8:
{
					tw.tw_hour = CVT2; cp++;
					tw.tw_min  = CVT2;
					BEGIN Z;
					}
	YY_BREAK
case 9:
{
					tw.tw_hour = CVT2; cp++;
					if (tw.tw_hour == 12)
						tw.tw_hour = 0;
					tw.tw_min  = CVT2;
					BEGIN Z;
					}
	YY_BREAK
case 10:
{
					tw.tw_hour = CVT2; cp++;
					if (tw.tw_hour != 12)
						tw.tw_hour += 12;
					tw.tw_min  = CVT2;
					BEGIN Z;
					}
	YY_BREAK
case 11:
{
					tw.tw_hour = CVT2;
					tw.tw_min  = CVT2;
					tw.tw_sec  = CVT2;
					BEGIN Z;
					}
	YY_BREAK
case 12:
{
					/*
					 * Luckly, 4 digit times in the range
					 * 1960-1999 aren't legal as hour
					 * and minutes. This rule must come
					 * the 4 digit hour and minute rule.
					 */
					cp += 2;
					tw.tw_year = CVT2;
					}
	YY_BREAK
case 13:
{
					tw.tw_hour = CVT2;
					tw.tw_min  = CVT2;
					BEGIN Z;
					}
	YY_BREAK
case 14:
ZONE(0 * 60);
	YY_BREAK
case 15:
ZONE(0 * 60);
	YY_BREAK
case 16:
ZONE(2 * 60);
	YY_BREAK
case 17:
ZONED(2 * 60);
	YY_BREAK
case 18:
ZONE(-5 * 60);
	YY_BREAK
case 19:
ZONED(-5 * 60);
	YY_BREAK
case 20:
ZONE(-6 * 60);
	YY_BREAK
case 21:
ZONED(-6 * 60);
	YY_BREAK
case 22:
ZONE(-7 * 60);
	YY_BREAK
case 23:
ZONED(-7 * 60);
	YY_BREAK
case 24:
ZONE(-8 * 60);
	YY_BREAK
case 25:
ZONED(-8 * 60);
	YY_BREAK
case 26:
ZONE(-(3 * 60 + 30));
	YY_BREAK
case 27:
ZONE(-4 * 60);
	YY_BREAK
case 28:
ZONED(-4 * 60);
	YY_BREAK
case 29:
ZONE(-9 * 60);
	YY_BREAK
case 30:
ZONED(-9 * 60);
	YY_BREAK
case 31:
ZONE(-10 * 60);
	YY_BREAK
case 32:
ZONED(-10 * 60);
	YY_BREAK
case 33:
ZONED(-1 * 60);
	YY_BREAK
case 34:
{
					tw.tw_zone = 60 * (('a'-1) - LC(*cp));
					EXPZONE; 
					}
	YY_BREAK
case 35:
{
					tw.tw_zone = 60 * ('a' - LC(*cp));
					EXPZONE; 
					}
	YY_BREAK
case 36:
{
					tw.tw_zone = 60 * (LC(*cp) - 'm');
					EXPZONE; 
					}
	YY_BREAK
case 37:
{
					cp++;
					tw.tw_zone = ((cp[0] * 10 + cp[1])
						     -('0' * 10   + '0'))*60
						    +((cp[2] * 10 + cp[3])
						     -('0' * 10   + '0'));
#ifdef	DSTXXX
					zonehack (&tw);
#endif	DSTXXX
					cp += 4;
					EXPZONE; 
					}
	YY_BREAK
case 38:
{
					cp++;
					tw.tw_zone = (('0' * 10   + '0')
						     -(cp[0] * 10 + cp[1]))*60
						    +(('0' * 10   + '0')
						     -(cp[2] * 10 + cp[3]));
#ifdef	DSTXXX
					zonehack (&tw);
#endif	DSTXXX
					cp += 4;
					EXPZONE; 
					}
	YY_BREAK
case 39:
case 40:
;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(Z):
return(&tw);
	YY_BREAK
case 42:
{
					/*
					 * We jammed; it's an error if we
					 * didn't parse anything.
					 */
					if (!gotdate || tw.tw_year == 0)
						return(0);
					return(&tw);
					}
	YY_BREAK
case 43:
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 390 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 390 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 389);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }


#ifdef	DSTXXX
#include <sys/types.h>
#ifndef	BSD42
#include <time.h>
#else	BSD42
#include <sys/time.h>
#endif	BSD42

static void
zonehack(tw)
    register struct tws *tw;
{
    register struct tm *tm;

    if (twclock (tw) == -1L)
	return;

    tm = localtime (&tw -> tw_clock);
    if (tm -> tm_isdst) {
	tw -> tw_flags |= TW_DST;
	tw -> tw_zone -= 60;
    }
}
#endif	DSTXXX
