#!/bin/sh
# Test a variant of a mailbox which caused debian bug 359167.
set -e

. ${MH_TEST_COMMON}

setup_test

THISDIR="${srcdir}/test/inc"

require_prog valgrind

TESTMBOX="$THISDIR/deb359167.mbox"

if [ "$(output_md5 "$TESTMBOX" | cut -d ' ' -f 1)" != "e6ac458b8cccba2b2fd866fb505aeb5e" ]; then 
  echo "Test mailbox has been corrupted"
  exit 1
fi

#
# valgrind refuses to run on a setuid/setgid program, so chmod inc so it
# isn't (just in case)
#

chmod 755 ${MH_INST_DIR}${bindir}/inc

valgrind --error-exitcode=1 --quiet inc -silent -file "$TESTMBOX"
