/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 39
#define YY_END_OF_BUFFER 40
static yyconst short int yy_accept[572] =
    {   0,
        0,    0,   40,   38,   37,   38,   38,   38,   38,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   38,   35,
       35,   36,   36,   36,   36,   36,   36,   36,   36,   36,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   14,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   28,

        0,   27,    0,   33,   21,   20,    0,   19,   18,    0,
        0,   15,   32,   31,    0,   17,   16,    0,    0,    0,
        0,   23,    0,   22,    0,   26,    0,   25,   24,    0,
        0,    0,    0,    0,    0,   30,   29,   12,   13,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   12,   13,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        9,    9,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    9,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        9,   10,   11,    7,    7,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    7,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    7,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        8,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    6,
        6,    6,    6,    6,    6,    6,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    5,    0,    5,    0,    0,
        0,    0,    0,    0,    3,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    5,    5,    5,    0,    0,
        8,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    5,    0,    0,    6,    6,
        0,    6,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    3,    0,    0,    6,    0,    0,    0,    0,
        0,    0,    6,    6,    0,    2,    4,    1,    1,    0,
        6,    0,    0,    0,    1,    0,    0,    1,    2,    4,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    5,    6,    1,    7,    8,    9,    8,
        8,    8,    8,    8,    8,    8,    8,   10,    1,    1,
        1,    1,    1,    1,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   29,   36,    1,
       11,    1,   12,    1,    1,    1,   13,   14,   15,   16,

       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   29,
       36,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[37] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[572] =
    {   0,
        0,    0,  869,  870,  870,   29,   31,   63,   30,   45,
      837,   31,  850,   44,   24,  841,   50,  870,   61,  870,
       66,   53,  850,   52,  870,   72,   22,  832,  846,   70,
       79,   82,   79,  831,   80,   82,  836,   83,   84,   86,
      829,   87,  827,   88,  118,   98,  119,  845,  829,  824,
      825,  822,  834,  820,  819,  818,  834,  816,  815,  832,
      824,  812,  811,  810,  815,  808,  807,   98,   93,  806,
      811,  804,  801,  802,  801,  800,  799,  798,  801,  802,
      794,  809,  870,  809,  792,  791,  100,  119,  102,  805,
      804,   99,  807,  792,  803,  800,  144,  804,  803,  870,

      135,  870,  114,  870,  870,  870,  131,  870,  870,  136,
       47,  870,  870,  870,  137,  870,  870,  139,  140,  144,
      812,  870,  153,  870,  159,  870,  152,  870,  870,  158,
      160,  162,  163,  169,  175,  870,  870,  164,  173,  783,
      793,  796,  796,  783,  159,  154,  774,  775,  778,  178,
      182,  794,  793,  194,  779,  771,  776,  767,  202,  797,
      785,  784,  794,  793,  774,  780,  767,  777,  760,  772,
      775,  756,  770,  768,  870,  870,  192,  193,  195,  204,
      197,  196,  205,  206,  782,  214,  212,  203,  228,  232,
      758,  757,  240,  779,  748,  765,  765,  242,  210,  760,

      759,  233,  762,  747,  758,  755,  735,  740,  767,  732,
      753,  749,  749,  739,  727,  746,  748,  729,  245,  735,
      727,  732,  723,  742,  752,  751,  732,  726,  736,  732,
      250,  253,  723,  722,  255,  744,  263,  743,  727,  713,
      267,  740,  711,  721,  724,  724,  711,  193,  237,  702,
      703,  706,  269,  697,  270,  715,  701,  717,  715,  274,
      715,  691,  710,  269,  273,  723,  692,  709,  709,  691,
      718,  705,  701,  692,  282,  278,  293,  704,  703,  288,
      291,  684,  677,  275,  695,  694,  291,  697,  682,  693,
      690,  286,  223,  303,  304,  307,  308,  309,  310,  704,

      311,  312,  313,  675,  702,  667,  685,  665,  314,  687,
      321,  329,  697,  681,  667,  660,  678,  664,  679,  333,
      690,  870,  870,  344,  346,  689,  688,  659,  669,  672,
      672,  659,  309,  291,  650,  651,  654,  348,  657,  649,
      654,  645,  664,  674,  673,  654,  648,  658,  654,  668,
      356,  639,  357,  632,  358,  309,  361,  637,  630,  635,
      662,  646,  652,  356,  369,  659,  364,  372,  374,  345,
      366,  373,  377,  380,  382,  383,  658,  388,  384,  386,
      404,  657,  626,  643,  643,  625,  652,  639,  635,  626,
      648,  387,  411,  647,  646,  645,  644,  615,  388,  614,

      616,  389,  394,  625,  421,  422,  617,  609,  614,  605,
      624,  634,  633,  614,  608,  618,  614,  426,  628,  427,
      627,  611,  597,  590,  608,  594,  609,  612,  399,  619,
      610,  598,  592,  585,  590,  582,  597,  597,  428,  430,
      610,  579,  596,  596,  578,  605,  592,  588,  579,  432,
      435,  444,  573,  566,  571,  598,  582,  439,  441,  582,
      581,  563,  579,  564,  562,  566,  449,  452,  589,  573,
      559,  552,  570,  556,  571,  454,  457,  465,  460,  463,
      582,  581,  580,  551,  570,  468,  566,  565,  547,  563,
      544,  558,  556,  476,  471,  479,  542,  535,  540,  567,

      551,  481,  565,  483,  485,  493,  495,  503,  564,  498,
      870,  529,  528,  547,  526,  545,  547,  528,  505,  556,
      555,  554,  553,  498,  508,  494,  415,  501,  870,  870,
      473,  870,  469,  419,  417,  405,  511,  391,  381,  513,
      521,  516,  870,  300,  296,  870,  309,  518,  523,  525,
      527,  529,  870,  870,  234,  250,  213,  531,  533,  207,
      870,  535,  537,  539,  541,  543,  545,  870,  870,  870,
      870
    } ;

static yyconst short int yy_def[572] =
    {   0,
      571,    1,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,

      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,

      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,

      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,

      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,

      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
        0
    } ;

static yyconst short int yy_nxt[907] =
    {   0,
        4,    4,    5,    6,    4,    7,    4,    8,    8,    4,
        9,    4,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   20,   21,   22,   23,   24,   25,   25,
       26,   27,   28,   25,   29,   30,   31,   31,   32,   32,
       60,   81,   48,   33,   34,   35,   55,   36,  159,   37,
       38,  160,   39,   61,   82,   40,   41,   49,   42,   58,
       50,   56,  161,   43,   45,   63,   44,   76,   46,   46,
       47,   47,   51,   65,   59,   52,   66,   53,   69,   73,
       64,   70,   77,   74,   78,   85,   87,   87,   79,   88,
       88,   67,   71,   68,   50,   55,   72,   58,   63,   66,

       86,   70,   76,   85,   80,   97,   97,  138,  138,   52,
       56,  144,   59,   64,   67,  154,   72,   77,   86,   45,
       45,  118,  120,  119,   46,   46,  139,  139,  121,  140,
       89,  145,  154,   90,  141,   91,  154,  154,  154,   92,
      154,  154,   93,   94,   95,  154,  156,  157,   96,  150,
      150,  151,  151,  154,  159,  155,  164,  160,  165,  159,
      154,  154,  160,  159,  159,  158,  160,  160,  166,  162,
      159,  175,  175,  160,  163,  167,  159,  171,  168,  160,
      176,  176,  182,  184,  183,  189,  190,  150,  150,  185,
      169,  170,  172,  219,  219,  154,  219,  219,  219,  173,

      174,  193,  193,  159,  219,  219,  219,  219,  541,  198,
      198,  222,  220,  219,  199,  219,  297,  200,  298,  201,
      227,  226,  563,  202,  338,  221,  203,  204,  205,  224,
      228,  225,  206,  223,  230,  231,  231,  243,  229,  232,
      232,  235,  244,  241,  236,  247,  219,  237,  237,  242,
      242,  275,  264,  265,  275,  340,  235,  276,  276,  562,
      277,  277,  280,  281,  235,  248,  299,  236,  241,  561,
      159,  159,  300,  160,  160,  159,  311,  311,  160,  284,
      312,  312,  285,  275,  286,  321,  321,  338,  287,  320,
      320,  288,  289,  290,  275,  324,  324,  291,  325,  325,

      321,  321,  328,  332,  338,  338,  339,  329,  338,  338,
      338,  338,  338,  338,  338,  159,  394,  394,  160,  341,
      376,  555,  355,  333,  346,  345,  377,  347,  356,  356,
      355,  554,  374,  342,  375,  553,  357,  357,  348,  343,
      363,  363,  364,  344,  349,  365,  406,  365,  366,  338,
      366,  367,  367,  368,  368,  381,  381,  159,  159,  355,
      160,  160,  355,  399,  399,  393,  393,  406,  394,  394,
      365,  405,  405,  365,  406,  406,  366,  408,  406,  405,
      405,  406,  409,  406,  406,  406,  400,  406,  159,  406,
      540,  160,  406,  401,  407,  431,  431,  414,  413,  402,

      403,  434,  410,  404,  415,  418,  458,  458,  419,  411,
      416,  420,  420,  436,  537,  412,  541,  417,  428,  428,
      429,  435,  365,  406,  542,  366,  437,  418,  418,  439,
      440,  419,  547,  450,  451,  467,  467,  468,  468,  476,
      476,  477,  478,  478,  477,  452,  485,  485,  486,  486,
      494,  479,  480,  494,  546,  502,  495,  495,  503,  496,
      496,  504,  504,  477,  505,  505,  502,  507,  507,  503,
      508,  508,  506,  506,  477,  511,  511,  494,  520,  520,
      494,  545,  502,  519,  519,  544,  520,  520,  525,  525,
      526,  526,  527,  527,  502,  502,  502,  503,  503,  503,

      526,  526,  504,  504,  502,  528,  528,  503,  543,  543,
      506,  506,  536,  536,  537,  539,  539,  540,  548,  548,
      549,  549,  541,  552,  552,  556,  556,  538,  550,  551,
      557,  557,  558,  558,  559,  559,  560,  560,  564,  564,
      565,  565,  566,  566,  567,  567,  568,  568,  568,  568,
      569,  569,  570,  570,  406,  406,  406,  494,  535,  534,
      533,  532,  531,  530,  529,  338,  502,  524,  406,  523,
      522,  521,  518,  517,  516,  515,  514,  513,  512,  510,
      509,  338,  338,  338,  501,  500,  499,  377,  498,  497,
      406,  493,  492,  491,  490,  489,  488,  487,  484,  338,

      483,  482,  481,  475,  474,  473,  406,  472,  471,  470,
      469,  406,  466,  465,  464,  463,  462,  461,  460,  459,
      219,  429,  457,  456,  455,  300,  454,  453,  338,  452,
      449,  448,  447,  446,  406,  406,  445,  444,  443,  442,
      441,  438,  433,  432,  430,  219,  219,  219,  355,  154,
      427,  426,  425,  338,  424,  423,  422,  421,  338,  406,
      365,  364,  398,  219,  397,  396,  395,  392,  391,  154,
      390,  389,  388,  387,  338,  338,  386,  385,  384,  383,
      382,  380,  379,  378,  373,  372,  371,  370,  369,  154,
      154,  275,  362,  361,  360,  185,  359,  358,  219,  354,

      353,  352,  351,  154,  350,  338,  337,  336,  335,  334,
      331,  330,  327,  326,  323,  322,  319,  318,  317,  219,
      316,  315,  314,  313,  219,  310,  309,  308,  307,  306,
      305,  304,  121,  303,  302,  301,  296,  295,  294,  293,
      292,  241,  283,  282,  154,  235,  279,  278,  274,  273,
      272,  271,  219,  219,  270,  269,  268,  267,  266,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  154,  254,
      253,  252,  251,  250,  249,  246,  245,  240,  239,  238,
      154,  234,  233,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  154,  154,  208,  207,  159,  197,

      196,  195,  194,  192,  191,  188,  187,  186,  181,  180,
      179,  178,  177,  154,  153,  152,  149,  148,  147,  146,
      143,  142,  137,  136,  135,  134,  133,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  117,  116,
      115,  114,  113,  112,  111,  110,  109,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   99,   98,   83,   74,
       62,   54,   84,   83,   75,   62,   57,   54,  571,    3,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,

      571,  571,  571,  571,  571,  571
    } ;

static yyconst short int yy_chk[907] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    6,    6,    7,    7,
       15,   27,    9,    7,    7,    7,   12,    7,  111,    7,
        7,  111,    7,   15,   27,    7,    7,    9,    7,   14,
       10,   12,  111,    7,    8,   17,    7,   24,    8,    8,
        8,    8,   10,   19,   14,   10,   19,   10,   21,   22,
       17,   21,   24,   22,   26,   30,   31,   31,   26,   32,
       32,   19,   21,   19,   33,   35,   21,   36,   38,   39,

       30,   40,   42,   44,   26,   46,   46,   87,   87,   33,
       35,   92,   36,   38,   39,  103,   40,   42,   44,   45,
       47,   68,   69,   68,   47,   47,   88,   88,   69,   89,
       45,   92,  107,   45,   89,   45,  101,  110,  115,   45,
      118,  119,   45,   45,   45,  120,  103,  107,   45,   97,
       97,   97,   97,  127,  123,  101,  119,  123,  120,  130,
      125,  131,  130,  132,  133,  110,  132,  133,  123,  115,
      134,  138,  138,  134,  118,  125,  135,  132,  127,  135,
      139,  139,  145,  146,  145,  150,  150,  151,  151,  146,
      130,  131,  133,  177,  178,  154,  179,  182,  181,  134,

      135,  154,  154,  159,  188,  180,  183,  184,  560,  159,
      159,  179,  177,  187,  159,  186,  248,  159,  248,  159,
      184,  183,  557,  159,  293,  178,  159,  159,  159,  181,
      186,  182,  159,  180,  188,  189,  189,  199,  187,  190,
      190,  193,  199,  198,  193,  202,  219,  193,  193,  198,
      198,  231,  219,  219,  232,  293,  235,  231,  231,  556,
      232,  232,  235,  235,  237,  202,  249,  237,  241,  555,
      253,  255,  249,  253,  255,  260,  264,  264,  260,  241,
      265,  265,  241,  275,  241,  276,  276,  292,  241,  275,
      275,  241,  241,  241,  277,  280,  280,  241,  281,  281,

      277,  277,  284,  287,  294,  295,  292,  284,  296,  297,
      298,  299,  301,  302,  303,  309,  356,  356,  309,  294,
      334,  547,  311,  287,  299,  298,  334,  301,  311,  311,
      312,  545,  333,  295,  333,  544,  312,  312,  302,  296,
      320,  320,  320,  297,  303,  324,  370,  325,  324,  338,
      325,  324,  324,  325,  325,  338,  338,  351,  353,  355,
      351,  353,  357,  364,  364,  355,  355,  371,  357,  357,
      365,  367,  367,  368,  372,  369,  368,  370,  373,  368,
      368,  374,  371,  375,  376,  379,  365,  380,  392,  378,
      539,  392,  538,  365,  369,  399,  399,  376,  375,  365,

      365,  402,  372,  365,  378,  381,  429,  429,  381,  373,
      379,  381,  381,  403,  536,  374,  527,  380,  393,  393,
      393,  402,  405,  406,  527,  405,  403,  418,  420,  406,
      406,  420,  535,  418,  418,  439,  439,  440,  440,  450,
      450,  450,  451,  451,  451,  452,  458,  458,  459,  459,
      467,  452,  452,  468,  534,  476,  467,  467,  476,  468,
      468,  476,  476,  476,  477,  477,  478,  479,  479,  478,
      480,  480,  478,  478,  478,  486,  486,  494,  495,  495,
      496,  533,  502,  494,  494,  531,  496,  496,  502,  502,
      504,  504,  505,  505,  506,  526,  507,  506,  526,  507,

      506,  506,  507,  507,  508,  510,  510,  508,  528,  528,
      508,  508,  519,  519,  519,  525,  525,  525,  537,  537,
      540,  540,  541,  542,  542,  548,  548,  524,  541,  541,
      549,  549,  550,  550,  551,  551,  552,  552,  558,  558,
      559,  559,  562,  562,  563,  563,  564,  564,  565,  565,
      566,  566,  567,  567,  523,  522,  521,  520,  518,  517,
      516,  515,  514,  513,  512,  509,  503,  501,  500,  499,
      498,  497,  493,  492,  491,  490,  489,  488,  487,  485,
      484,  483,  482,  481,  475,  474,  473,  472,  471,  470,
      469,  466,  465,  464,  463,  462,  461,  460,  457,  456,

      455,  454,  453,  449,  448,  447,  446,  445,  444,  443,
      442,  441,  438,  437,  436,  435,  434,  433,  432,  431,
      430,  428,  427,  426,  425,  424,  423,  422,  421,  419,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  404,  401,  400,  398,  397,  396,  395,  394,  391,
      390,  389,  388,  387,  386,  385,  384,  383,  382,  377,
      366,  363,  362,  361,  360,  359,  358,  354,  352,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  337,  336,  335,  332,  331,  330,  329,  328,  327,
      326,  321,  319,  318,  317,  316,  315,  314,  313,  310,

      308,  307,  306,  305,  304,  300,  291,  290,  289,  288,
      286,  285,  283,  282,  279,  278,  274,  273,  272,  271,
      270,  269,  268,  267,  266,  263,  262,  261,  259,  258,
      257,  256,  254,  252,  251,  250,  247,  246,  245,  244,
      243,  242,  240,  239,  238,  236,  234,  233,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  201,  200,  197,  196,  195,
      194,  192,  191,  185,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  158,

      157,  156,  155,  153,  152,  149,  148,  147,  144,  143,
      142,  141,  140,  121,   99,   98,   96,   95,   94,   93,
       91,   90,   86,   85,   84,   82,   81,   80,   79,   78,
       77,   76,   75,   74,   73,   72,   71,   70,   67,   66,
       65,   64,   63,   62,   61,   60,   59,   58,   57,   56,
       55,   54,   53,   52,   51,   50,   49,   48,   43,   41,
       37,   34,   29,   28,   23,   16,   13,   11,    3,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,
      571,  571,  571,  571,  571,  571,  571,  571,  571,  571,

      571,  571,  571,  571,  571,  571
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "dtimep.lex"
#define INITIAL 0
#line 3 "dtimep.lex"
#include <h/nmh.h>
#include <h/tws.h>

#define YY_NO_UNPUT
#define YY_DECL struct tws * dparsetime(char *lexstr)

#define yyterminate() (void)yy_delete_buffer(lexhandle); \
  if(!(tw.tw_flags & TW_SUCC)) { \
    return (struct tws *)NULL; \
  } \
  if(tw.tw_year < 1960) \
    tw.tw_year += 1900; \
  if(tw.tw_year < 1960) \
    tw.tw_year += 100; \
  return(&tw)

/*
 * Patchable flag that says how to interpret NN/NN/NN dates. When
 * true, we do it European style: DD/MM/YY. When false, we do it
 * American style: MM/DD/YY.  Of course, these are all non-RFC822
 * compliant.
 */
int europeandate = 0;

/*
 * Table to convert month names to numeric month.  We use the
 * fact that the low order 5 bits of the sum of the 2nd & 3rd
 * characters of the name is a hash with no collisions for the 12
 * valid month names.  (The mask to 5 bits maps any combination of
 * upper and lower case into the same hash value).
 */
static int month_map[] = {
	0,
	6,	/* 1 - Jul */
	3,	/* 2 - Apr */
	5,	/* 3 - Jun */
	0,
	10,	/* 5 - Nov */
	0,
	1,	/* 7 - Feb */
	11,	/* 8 - Dec */
	0,
	0,
	0,
	0,
	0,
	0,
	0,	/*15 - Jan */
	0,
	0,
	0,
	2,	/*19 - Mar */
	0,
	8,	/*21 - Sep */
	0,
	9,	/*23 - Oct */
	0,
	0,
	4,	/*26 - May */
	0,
	7	/*28 - Aug */
};

/*
 * Same trick for day-of-week using the hash function
 *  (c1 & 7) + (c2 & 4)
 */
static int day_map[] = {
	0,
	0,
	0,
	6,	/* 3 - Sat */
	4,	/* 4 - Thu */
	0,
	5,	/* 6 - Fri */
	0,	/* 7 - Sun */
	2,	/* 8 - Tue */
	1	/* 9 - Mon */,
	0,
	3	/*11 - Wed */
};

#define INIT()   { cp = yytext;}
#define SETWDAY() { cp++; \
                   tw.tw_wday= day_map[(cp[0] & 7) + (cp[1] & 4)]; \
                   tw.tw_flags &= ~TW_SDAY; tw.tw_flags |= TW_SEXP; \
                   SKIPA(); }
#define SETMON() { cp++; \
                   tw.tw_mon = month_map[(cp[0] + cp[1]) & 0x1f]; \
  		   SKIPA(); }
#define SETMON_NUM() { tw.tw_mon = atoi(cp)-1; \
  		   SKIPD(); }
#define SETYEAR() { tw.tw_year = atoi(cp); \
  		   SKIPD(); }
#define SETDAY() { tw.tw_mday = atoi(cp); \
                   tw.tw_flags |= TW_YES; \
  		   SKIPD(); }
#define SETTIME() { tw.tw_hour = atoi(cp); \
                    cp += 2; \
                    SKIPTOD(); \
                    tw.tw_min = atoi(cp); \
                    cp += 2; \
                    if(*cp == ':') { tw.tw_sec = atoi(++cp); SKIPD(); } \
                    }
#define SETZONE(x) { tw.tw_zone = ((x)/100)*60+(x)%100; \
                     tw.tw_flags |= TW_SZEXP; \
                     SKIPD(); }
#define SETDST()   { tw.tw_flags |= TW_DST; }
#define SKIPD()  { while ( isdigit(*cp++) ) ; \
                      --cp; }
#define SKIPTOD()  { while ( !isdigit(*cp++) ) ; \
                      --cp; }
#define SKIPA()  { while ( isalpha(*cp++) ) ; \
                      --cp; }
#define SKIPTOA()  { while ( !isalpha(*cp++) ) ; \
                      --cp; }
#define SKIPSP()  { while ( isspace(*cp++) ) ; \
                      --cp; }
#define SKIPTOSP()  { while ( !isspace(*cp++) ) ; \
                      --cp; }

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 159 "dtimep.lex"


  
  YY_BUFFER_STATE lexhandle;

  register char *cp;  /* *cp is internal to the lexing function yylex() */
  static struct tws tw; 

  memset(&tw,0,sizeof(struct tws));
  lexhandle = yy_scan_string(lexstr);



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 572 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 870 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 171 "dtimep.lex"
{
                                     INIT();
				     SETWDAY();
				     SKIPTOA();
				     SETMON();
				     SKIPTOD();
				     SETDAY();
				     SKIPTOD();
				     SETTIME();
				     SKIPTOD();
				     SETYEAR();
                                  }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 184 "dtimep.lex"
{
                                     INIT();
				     SETWDAY();
				     SKIPTOD();
				     SETDAY();
				     SKIPTOA();
				     SETMON();
				     SKIPTOD();
				     SETYEAR();
				     SKIPTOD();
				     SETTIME();
                                  }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 196 "dtimep.lex"
{
                                     INIT();
				     SETDAY();
				     SKIPTOA();
				     SETMON();
				     SKIPTOD();
				     SETYEAR();
				     SKIPTOD();
				     SETTIME();
                                  }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 206 "dtimep.lex"
{
                                     INIT();
				     SETWDAY();
				     SKIPTOA();
				     SETMON();
				     SKIPTOD();
				     SETDAY();
				     SKIPTOD();
				     SETYEAR();
				     SKIPTOD();
				     SETTIME();
                                  }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 218 "dtimep.lex"
{
                                     INIT();
				     SETWDAY();
				     SKIPTOA();
				     SETMON();
				     SKIPTOD();
				     SETDAY();
				     SKIPTOD();
				     SETYEAR();
                                  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 228 "dtimep.lex"
{
                                     INIT();
				     SETMON();
				     SKIPTOD();
				     SETDAY();
				     SKIPTOD();
				     SETYEAR();
				     SKIPTOA();
				     SETWDAY();
                                  }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 238 "dtimep.lex"
{
                                     INIT();
				     SETMON();
				     SKIPTOD();
				     SETDAY();
				     SKIPTOD();
				     SETYEAR();
                                  }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 246 "dtimep.lex"
{
                                     INIT();
				     if(europeandate) {
				       /* DD/MM/YY */
				     SETDAY();
				     SKIPTOD();
				     SETMON_NUM();
				     } else {
				       /* MM/DD/YY */
				     SETMON_NUM();
				     SKIPTOD();
				     SETDAY();
				     }
				     SKIPTOD();
				     SETYEAR();
				     SKIPTOD();
				     SETTIME();
                                  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 264 "dtimep.lex"
{
                                     INIT();
				     if(europeandate) {
				       /* DD/MM/YY */
				     SETDAY();
				     SKIPTOD();
				     SETMON_NUM();
				     } else {
				       /* MM/DD/YY */
				     SETMON_NUM();
				     SKIPTOD();
				     SETDAY();
				     }
				     SKIPTOD();
				     SETYEAR();
                                  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 281 "dtimep.lex"

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 282 "dtimep.lex"
tw.tw_hour += 12;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 284 "dtimep.lex"
{
                                    INIT();
                                    SKIPTOD();
                                    SETZONE(atoi(cp));
                                }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 289 "dtimep.lex"
{
                                    INIT();
                                    SKIPTOD();
                                    SETZONE(-atoi(cp));
                                }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 294 "dtimep.lex"
INIT(); SETZONE(0);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 295 "dtimep.lex"
INIT(); SETZONE(0);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 296 "dtimep.lex"
INIT(); SETZONE(200);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 297 "dtimep.lex"
INIT(); SETDST(); SETZONE(2);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 298 "dtimep.lex"
INIT(); SETZONE(-500);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 299 "dtimep.lex"
INIT(); SETDST(); SETZONE(-500);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 300 "dtimep.lex"
INIT(); SETZONE(-600);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 301 "dtimep.lex"
INIT(); SETDST(); SETZONE(-600);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 302 "dtimep.lex"
INIT(); SETZONE(-700);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 303 "dtimep.lex"
INIT(); SETDST(); SETZONE(-700);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 304 "dtimep.lex"
INIT(); SETZONE(-800);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 305 "dtimep.lex"
INIT(); SETDST(); SETZONE(-800);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 306 "dtimep.lex"
INIT(); SETZONE(-330);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 307 "dtimep.lex"
INIT(); SETZONE(-400);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 308 "dtimep.lex"
INIT(); SETDST(); SETZONE(-400);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 309 "dtimep.lex"
INIT(); SETZONE(-900);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 310 "dtimep.lex"
INIT(); SETDST(); SETZONE(-900);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 311 "dtimep.lex"
INIT(); SETZONE(-1000);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 312 "dtimep.lex"
INIT(); SETDST(); SETZONE(-1000);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 313 "dtimep.lex"
INIT(); SETDST(); SETZONE(-100);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 314 "dtimep.lex"
{
                                       INIT();
                                       SETZONE(100*(('a'-1) - tolower(*cp)));
			}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 318 "dtimep.lex"
{
                                       INIT();
                                       SETZONE(100*('a' - tolower(*cp)));
			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 322 "dtimep.lex"
{
                                       INIT();
                                       SETZONE(100*(tolower(*cp) - 'm'));
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 328 "dtimep.lex"

	YY_BREAK
case 38:
YY_RULE_SETUP
#line 329 "dtimep.lex"

	YY_BREAK
case 39:
YY_RULE_SETUP
#line 333 "dtimep.lex"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 572 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 572 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 571);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 333 "dtimep.lex"
