/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 38
#define YY_END_OF_BUFFER 39
static yyconst short int yy_accept[614] =
    {   0,
        0,    0,   39,   37,   37,   37,   37,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   37,   35,   35,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   37,   34,
       34,   34,   34,   34,   34,   37,   35,   36,   36,   36,
       36,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   14,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   28,
       27,    0,    0,   33,   21,   20,    0,   19,   18,    0,
        0,   15,   32,   31,   17,   16,    0,    0,    0,   23,
       22,    0,    0,    0,   26,    0,    0,   25,   24,    0,
        0,    0,    0,    0,    0,   30,   29,    0,    0,   12,
       13,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   12,   13,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    9,    9,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    9,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    9,    7,    7,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   10,   11,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    7,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    7,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    8,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    6,    6,    6,    6,    6,    6,    6,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    5,    0,    5,
        0,    0,    0,    0,    0,    0,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    5,    5,    5,
        0,    0,    8,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    5,    0,    0,
        6,    6,    0,    6,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    3,    0,    0,    6,    0,    0,
        0,    0,    0,    0,    6,    6,    0,    2,    4,    1,

        1,    0,    6,    0,    0,    0,    1,    0,    0,    1,
        2,    4,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    5,    6,    1,    7,    8,    9,    8,
        8,    8,    8,    8,    8,    8,    8,   10,    1,    1,
        1,    1,    1,    1,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   21,   22,   23,   24,   25,
       26,   26,   27,   28,   29,   26,   30,   26,   31,    1,
       32,    1,   33,    1,    1,    1,   34,   35,   36,   37,

       38,   16,   39,   40,   41,   42,   21,   43,   44,   45,
       46,   47,   26,   48,   49,   50,   51,   52,   30,   26,
       53,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[614] =
    {   0,
        0,    0,  988,  989,   46,   48,   96,   62,  960,   48,
      948,   53,   26,  963,   58,  989,   80,  989,   83,   54,
      948,   64,  989,   74,   18,  955,  944,   92,  105,   85,
      932,   74,   78,  936,   84,  101,  105,   91,  104,  929,
      106,  136,  138,  134,  951,  135,  142,  955,  143,  144,
      145,  949,  146,  947,  149,  128,  925,  129,  130,  929,
      131,  137,  138,  923,  144,  921,  145,  193,  175,  183,
      942,  941,  920,  928,  938,  937,  936,  927,  934,  933,
      925,  918,  930,  929,  928,  927,  926,  908,   75,  924,
      923,  143,  905,  921,  896,  897,  918,  917,  894,  896,

      897,  890,  902,  989,  902,  910,  909,  902,  888,  884,
      883,  882,  881,  880,  879,  878,  877,  876,  875,  874,
      873,  872,  871,  870,  869,  868,  867,  866,  189,  191,
       77,  877,  876,  154,  879,  866,  875,  872,  215,  989,
      989,  162,  190,  989,  989,  989,  206,  989,  989,  199,
      209,  989,  989,  989,  989,  989,  200,  204,  210,  989,
      989,  216,  907,  223,  989,  217,  208,  989,  989,  224,
      229,  231,  238,  248,  254,  989,  989,  875,  874,  253,
      255,  858,  866,  868,  868,  857,  189,  217,  849,  850,
      852,  258,  265,  272,  855,  848,  852,  844,  298,  892,

      859,  858,  889,  888,  849,  854,  843,  851,  837,  846,
      849,  833,  844,  842,  847,  846,  989,  989,  243,  247,
      256,  267,  275,  271,  281,  274,  875,  285,  283,  280,
      280,  282,  329,  874,  825,  839,  839,  293,  245,  834,
      833,  277,  836,  823,  832,  829,  813,  817,  862,  810,
      827,  823,  823,  815,  805,  820,  822,  806,  832,  831,
      337,  809,  802,  806,  798,  814,  845,  844,  805,  800,
      808,  804,  346,  348,  350,  839,  303,  838,  801,  790,
      358,  835,  788,  796,  798,  798,  787,  306,  288,  779,
      780,  782,  311,  775,  359,  789,  778,  791,  789,  360,

      789,  769,  784,  776,  775,  295,  358,  816,  767,  781,
      781,  766,  811,  777,  773,  766,  368,  375,  385,  380,
      382,  761,  755,  324,  769,  768,  345,  771,  758,  767,
      764,  276,  361,  371,  351,  366,  384,  395,  291,  799,
      396,  399,  403,  752,  797,  745,  759,  743,  406,  761,
      761,  760,  411,  413,  790,  753,  742,  736,  750,  739,
      751,  415,  783,  427,  438,  782,  781,  734,  742,  744,
      744,  733,  371,  378,  725,  726,  728,  440,  731,  724,
      728,  720,  736,  767,  766,  727,  722,  730,  726,  761,
      425,  714,  436,  708,  989,  989,  442,  446,  450,  712,

      706,  710,  755,  718,  745,  448,  458,  752,  453,  461,
      426,  462,  437,  463,  466,  469,  471,  470,  751,  474,
      475,  476,  482,  750,  701,  715,  715,  700,  745,  711,
      707,  700,  741,  477,  484,  740,  739,  738,  737,  690,
      487,  689,  690,  447,  449,  697,  499,  516,  691,  684,
      688,  680,  696,  727,  726,  687,  682,  690,  686,  521,
      721,  514,  720,  683,  672,  666,  680,  669,  681,  705,
      506,  712,  703,  671,  666,  660,  664,  657,  669,  669,
      519,  523,  703,  654,  668,  668,  653,  698,  664,  660,
      653,  525,  528,  537,  648,  642,  646,  691,  654,  532,

      534,  654,  653,  638,  651,  639,  637,  640,  542,  545,
      682,  645,  634,  628,  642,  631,  643,  547,  550,  558,
      553,  556,  675,  674,  673,  626,  663,  561,  638,  637,
      622,  635,  619,  630,  628,  569,  564,  572,  617,  611,
      615,  660,  623,  574,  658,  576,  578,  586,  588,  596,
      657,  591,  989,  605,  604,  619,  602,  617,  619,  603,
      598,  649,  648,  647,  646,  573,  601,  587,  408,  594,
      989,  989,  545,  989,  541,  495,  483,  500,  604,  503,
      493,  606,  614,  609,  989,  446,  444,  989,  449,  611,
      616,  618,  620,  622,  989,  989,  353,  323,  116,  624,

      626,   94,  989,  628,  630,  632,  634,  636,  638,  989,
      989,  989,  989
    } ;

static yyconst short int yy_def[614] =
    {   0,
      613,    1,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,

      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,

      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,

      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,

      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,

      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,

      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,    0
    } ;

static yyconst short int yy_nxt[1043] =
    {   0,
        4,    4,    4,    5,    4,    6,    4,    7,    7,    4,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,    4,   30,   31,   32,   11,   33,   34,   35,
       16,   36,   18,   37,   38,   21,   39,   23,   24,   25,
       40,   23,   41,   42,   42,   43,   43,  102,   44,   45,
       46,   76,   47,   81,   48,   49,   79,   50,  103,   51,
       52,   84,   53,   82,   77,   71,   54,   97,   55,   80,
       94,   56,   57,   58,   85,   59,   60,   61,   72,   62,
       98,   63,   64,   86,   65,  583,   90,   68,   66,   95,

       67,   69,   69,   70,   70,  106,   87,   99,   73,   91,
      113,  100,   74,   88,  115,  108,   92,  158,  107,  159,
      118,  110,  114,  182,  101,  605,  116,  183,   93,  109,
       89,   73,  119,  111,   88,   74,   95,  120,   92,  124,
      125,  122,  127,  129,  129,  130,  130,   71,   76,  121,
       93,   89,  126,  123,  128,   79,   84,   86,   90,   97,
       72,   77,  106,  194,  110,  113,  115,  118,   80,   85,
       87,   91,   98,  120,  122,  107,  111,  114,  116,  119,
      125,  127,  139,  139,   68,  121,  123,  186,   69,   69,
      162,  194,  126,  128,   68,  163,  180,  180,  181,  181,

      194,  194,  195,  131,  187,  194,  132,  194,  133,  194,
      199,  194,  134,  200,  135,  136,  137,  194,  194,  138,
      192,  192,  193,  193,  199,  199,  131,  200,  200,  132,
      194,  224,  199,  225,  134,  200,  135,  136,  137,  199,
      196,  138,  200,  197,  261,  201,  198,  204,  261,  199,
      202,  205,  200,  208,  207,  199,  203,  261,  200,  206,
      217,  217,  218,  218,  226,  231,  232,  211,  261,  227,
      192,  192,  261,  194,  209,  261,  261,  378,  210,  233,
      233,  261,  261,  262,  261,  212,  261,  273,  273,  274,
      274,  283,  378,  264,  281,  284,  213,  263,  214,  199,

      282,  282,  353,  353,  275,  238,  238,  276,  239,  269,
      287,  240,  199,  241,  265,  200,  379,  242,  268,  243,
      244,  245,  270,  267,  246,  266,  386,  288,  271,  272,
      275,  239,  604,  276,  240,  339,  277,  277,  261,  242,
      340,  243,  244,  245,  306,  307,  246,  317,  337,  317,
      338,  275,  378,  318,  318,  319,  319,  320,  321,  281,
      199,  199,  378,  200,  200,  354,  354,  378,  324,  317,
      368,  325,  378,  326,  369,  362,  362,  327,  372,  328,
      329,  330,  363,  363,  331,  378,  317,  364,  364,  365,
      365,  324,  363,  363,  325,  373,  378,  378,  382,  327,

      378,  328,  329,  330,  378,  603,  331,  199,  381,  583,
      200,  380,  397,  416,  397,  417,  383,  584,  398,  398,
      399,  399,  405,  405,  406,  418,  199,  448,  407,  200,
      419,  408,  385,  387,  409,  409,  384,  199,  448,  407,
      200,  378,  408,  397,  388,  410,  410,  423,  423,  435,
      435,  397,  389,  436,  436,  441,  441,  436,  436,  407,
      447,  447,  407,  448,  448,  408,  449,  448,  447,  447,
      448,  448,  448,  442,  451,  448,  448,  448,  199,  443,
      476,  200,  597,  460,  444,  445,  461,  446,  478,  462,
      462,  470,  470,  471,  473,  473,  596,  477,  595,  479,

      407,  443,  582,  408,  448,  456,  444,  445,  455,  579,
      452,  457,  450,  500,  500,  460,  453,  448,  461,  589,
      458,  454,  460,  481,  482,  459,  509,  509,  492,  493,
      510,  510,  518,  518,  519,  520,  520,  519,  494,  527,
      527,  528,  528,  536,  521,  522,  536,  588,  544,  537,
      537,  545,  538,  538,  546,  546,  519,  547,  547,  544,
      549,  549,  545,  550,  550,  548,  548,  519,  553,  553,
      536,  562,  562,  536,  587,  544,  561,  561,  586,  562,
      562,  567,  567,  568,  568,  569,  569,  544,  544,  544,
      545,  545,  545,  568,  568,  546,  546,  544,  570,  570,

      545,  585,  585,  548,  548,  578,  578,  579,  581,  581,
      582,  590,  590,  591,  591,  583,  594,  594,  598,  598,
      580,  592,  593,  599,  599,  600,  600,  601,  601,  602,
      602,  606,  606,  607,  607,  608,  608,  609,  609,  610,
      610,  610,  610,  611,  611,  612,  612,  448,  448,  448,
      536,  577,  576,  575,  574,  573,  572,  571,  378,  544,
      566,  448,  565,  564,  563,  560,  559,  558,  557,  556,
      555,  554,  552,  551,  378,  378,  378,  543,  542,  541,
      419,  540,  539,  448,  535,  534,  533,  532,  531,  530,
      529,  526,  378,  525,  524,  523,  517,  516,  515,  448,

      514,  513,  512,  511,  448,  508,  507,  506,  505,  504,
      503,  502,  501,  261,  471,  499,  498,  497,  340,  496,
      495,  378,  494,  491,  490,  489,  488,  448,  448,  487,
      486,  485,  484,  483,  480,  475,  474,  472,  261,  261,
      261,  397,  194,  469,  468,  467,  378,  466,  465,  464,
      463,  378,  448,  407,  406,  440,  261,  439,  438,  437,
      434,  433,  194,  432,  431,  430,  429,  378,  378,  428,
      427,  426,  425,  424,  422,  421,  420,  415,  414,  413,
      412,  411,  194,  194,  317,  404,  403,  402,  227,  401,
      400,  261,  396,  395,  394,  393,  392,  391,  194,  390,

      378,  377,  376,  375,  374,  371,  370,  367,  366,  361,
      360,  359,  261,  358,  357,  356,  355,  261,  352,  351,
      350,  349,  348,  347,  346,  345,  344,  163,  343,  342,
      341,  336,  335,  334,  333,  332,  281,  323,  322,  194,
      275,  316,  315,  314,  313,  261,  261,  312,  311,  310,
      309,  308,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  194,  294,  293,  292,  291,  290,  289,
      286,  285,  280,  279,  278,  194,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  194,
      194,  248,  247,  199,  237,  236,  235,  234,  230,  229,

      228,  223,  222,  221,  220,  219,  216,  215,  194,  191,
      190,  189,  188,  185,  184,  177,  176,  169,  168,  165,
      161,  160,  156,  155,  154,  153,  152,  149,  148,  146,
      145,  144,  141,  140,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      161,  160,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  140,
      104,  124,  117,  112,  104,   94,   83,   75,  104,  117,
      112,  105,  104,   96,   83,   78,   75,  613,    3,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,

      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613
    } ;

static yyconst short int yy_chk[1043] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    5,    6,    6,   25,    6,    6,
        6,   10,    6,   13,    6,    6,   12,    6,   25,    6,
        6,   15,    6,   13,   10,    8,    6,   22,    6,   12,
       20,    6,    6,    6,   15,    6,    6,    6,    8,    6,
       22,    6,    6,   17,    6,  602,   19,    7,    6,   20,

        6,    7,    7,    7,    7,   28,   17,   24,    8,   19,
       32,   24,    8,   17,   33,   29,   19,   89,   28,   89,
       35,   30,   32,  131,   24,  599,   33,  131,   19,   29,
       17,   30,   35,   30,   36,   30,   38,   36,   37,   38,
       39,   37,   41,   42,   42,   43,   43,   44,   46,   36,
       37,   36,   39,   37,   41,   47,   49,   50,   51,   53,
       44,   46,   55,  142,   56,   58,   59,   61,   47,   49,
       50,   51,   53,   62,   63,   55,   56,   58,   59,   61,
       65,   67,   69,   69,   70,   62,   63,  134,   70,   70,
       92,  143,   65,   67,   68,   92,  129,  129,  130,  130,

      150,  157,  142,   68,  134,  158,   68,  147,   68,  167,
      151,  159,   68,  151,   68,   68,   68,  162,  166,   68,
      139,  139,  139,  139,  164,  170,   68,  164,  170,   68,
      171,  187,  172,  187,   68,  172,   68,   68,   68,  173,
      143,   68,  173,  147,  219,  151,  150,  159,  220,  174,
      157,  162,  174,  167,  166,  175,  158,  221,  175,  164,
      180,  180,  181,  181,  188,  192,  192,  172,  222,  188,
      193,  193,  224,  194,  170,  226,  223,  332,  171,  194,
      194,  230,  225,  219,  229,  173,  228,  231,  231,  232,
      232,  239,  339,  221,  238,  239,  174,  220,  175,  199,

      238,  238,  306,  306,  277,  199,  199,  277,  199,  226,
      242,  199,  293,  199,  222,  293,  332,  199,  225,  199,
      199,  199,  228,  224,  199,  223,  339,  242,  229,  230,
      233,  199,  598,  233,  199,  289,  233,  233,  261,  199,
      289,  199,  199,  199,  261,  261,  199,  273,  288,  274,
      288,  275,  335,  273,  273,  274,  274,  275,  275,  281,
      295,  300,  333,  295,  300,  307,  307,  336,  281,  317,
      324,  281,  334,  281,  324,  317,  317,  281,  327,  281,
      281,  281,  318,  318,  281,  337,  319,  320,  320,  321,
      321,  281,  319,  319,  281,  327,  338,  341,  335,  281,

      342,  281,  281,  281,  343,  597,  281,  349,  334,  569,
      349,  333,  353,  373,  354,  373,  336,  569,  353,  353,
      354,  354,  362,  362,  362,  374,  391,  411,  364,  391,
      374,  364,  338,  341,  364,  364,  337,  393,  413,  365,
      393,  378,  365,  397,  342,  365,  365,  378,  378,  397,
      397,  399,  343,  398,  398,  406,  406,  399,  399,  407,
      409,  409,  410,  412,  414,  410,  411,  415,  410,  410,
      416,  418,  417,  407,  413,  420,  421,  422,  434,  407,
      444,  434,  589,  423,  407,  407,  423,  407,  445,  423,
      423,  435,  435,  435,  441,  441,  587,  444,  586,  445,

      447,  407,  581,  447,  580,  418,  407,  407,  417,  578,
      414,  420,  412,  471,  471,  462,  415,  448,  462,  577,
      421,  416,  460,  448,  448,  422,  481,  481,  460,  460,
      482,  482,  492,  492,  492,  493,  493,  493,  494,  500,
      500,  501,  501,  509,  494,  494,  510,  576,  518,  509,
      509,  518,  510,  510,  518,  518,  518,  519,  519,  520,
      521,  521,  520,  522,  522,  520,  520,  520,  528,  528,
      536,  537,  537,  538,  575,  544,  536,  536,  573,  538,
      538,  544,  544,  546,  546,  547,  547,  548,  568,  549,
      548,  568,  549,  548,  548,  549,  549,  550,  552,  552,

      550,  570,  570,  550,  550,  561,  561,  561,  567,  567,
      567,  579,  579,  582,  582,  583,  584,  584,  590,  590,
      566,  583,  583,  591,  591,  592,  592,  593,  593,  594,
      594,  600,  600,  601,  601,  604,  604,  605,  605,  606,
      606,  607,  607,  608,  608,  609,  609,  565,  564,  563,
      562,  560,  559,  558,  557,  556,  555,  554,  551,  545,
      543,  542,  541,  540,  539,  535,  534,  533,  532,  531,
      530,  529,  527,  526,  525,  524,  523,  517,  516,  515,
      514,  513,  512,  511,  508,  507,  506,  505,  504,  503,
      502,  499,  498,  497,  496,  495,  491,  490,  489,  488,

      487,  486,  485,  484,  483,  480,  479,  478,  477,  476,
      475,  474,  473,  472,  470,  469,  468,  467,  466,  465,
      464,  463,  461,  459,  458,  457,  456,  455,  454,  453,
      452,  451,  450,  449,  446,  443,  442,  440,  439,  438,
      437,  436,  433,  432,  431,  430,  429,  428,  427,  426,
      425,  424,  419,  408,  405,  404,  403,  402,  401,  400,
      394,  392,  390,  389,  388,  387,  386,  385,  384,  383,
      382,  381,  380,  379,  377,  376,  375,  372,  371,  370,
      369,  368,  367,  366,  363,  361,  360,  359,  358,  357,
      356,  355,  352,  351,  350,  348,  347,  346,  345,  344,

      340,  331,  330,  329,  328,  326,  325,  323,  322,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  305,  304,
      303,  302,  301,  299,  298,  297,  296,  294,  292,  291,
      290,  287,  286,  285,  284,  283,  282,  280,  279,  278,
      276,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      241,  240,  237,  236,  235,  234,  227,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  198,  197,  196,  195,  191,  190,

      189,  186,  185,  184,  183,  182,  179,  178,  163,  138,
      137,  136,  135,  133,  132,  128,  127,  126,  125,  124,
      123,  122,  121,  120,  119,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  107,  106,  105,  103,
      102,  101,  100,   99,   98,   97,   96,   95,   94,   93,
       91,   90,   88,   87,   86,   85,   84,   83,   82,   81,
       80,   79,   78,   77,   76,   75,   74,   73,   72,   71,
       66,   64,   60,   57,   54,   52,   48,   45,   40,   34,
       31,   27,   26,   21,   14,   11,    9,    3,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,

      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "dtimep.lex"
#define INITIAL 0
#line 6 "dtimep.lex"
#include <h/nmh.h>
#include <h/tws.h>

  /* Since we're looking at a string at a time, don't worry about
   *  wrapping to the next buffer.
   */
#define yywrap() 1
#define YY_SKIP_YYWRAP

#define YY_NO_UNPUT

  /* This is the tricky thing that makes this function cool.  We
   *  replace the traditional int yylex(void) declaration with our
   *  dparsetime() declaration, essentially piggy-backing off the
   *  utility of the yylex() function and adding what we need to make
   *  the parsing function useful to us.
   */
#define YY_DECL struct tws *dparsetime(char *lexstr)

  /* yyerminate() is called after the input string is matched to
   * completion (actually, when the lexer reaches an EOF).  The only
   * thing that really needs to be in this macro function is the
   * return call, which must be substituted inline into dparsetime.
   */

#define yyterminate() (void)yy_delete_buffer(lexhandle); \
  if(!(tw.tw_flags & TW_SUCC)) { \
    return (struct tws *)NULL; \
  } \
  if(tw.tw_year < 1960) \
    tw.tw_year += 1900; \
  if(tw.tw_year < 1960) \
    tw.tw_year += 100; \
  return(&tw)

/*
 * Patchable flag that says how to interpret NN/NN/NN dates. When
 * true, we do it European style: DD/MM/YY. When false, we do it
 * American style: MM/DD/YY.  Of course, these are all non-RFC822
 * compliant.
 */
int europeandate = 0;

/*
 * Table to convert month names to numeric month.  We use the
 * fact that the low order 5 bits of the sum of the 2nd & 3rd
 * characters of the name is a hash with no collisions for the 12
 * valid month names.  (The mask to 5 bits maps any combination of
 * upper and lower case into the same hash value).
 */
static int month_map[] = {
	0,
	6,	/* 1 - Jul */
	3,	/* 2 - Apr */
	5,	/* 3 - Jun */
	0,
	10,	/* 5 - Nov */
	0,
	1,	/* 7 - Feb */
	11,	/* 8 - Dec */
	0,
	0,
	0,
	0,
	0,
	0,
	0,	/*15 - Jan */
	0,
	0,
	0,
	2,	/*19 - Mar */
	0,
	8,	/*21 - Sep */
	0,
	9,	/*23 - Oct */
	0,
	0,
	4,	/*26 - May */
	0,
	7	/*28 - Aug */
};

/*
 * Same trick for day-of-week using the hash function
 *  (c1 & 7) + (c2 & 4)
 */
static int day_map[] = {
	0,
	0,
	0,
	6,	/* 3 - Sat */
	4,	/* 4 - Thu */
	0,
	5,	/* 6 - Fri */
	0,	/* 7 - Sun */
	2,	/* 8 - Tue */
	1	/* 9 - Mon */,
	0,
	3	/*11 - Wed */
};

/* The SET* macros will parse for the appropriate field, and leave the
 * cp pointer at the first character after the desired field. Be
 * careful with variable-length fields or alpha-num mixes.

 * The SKIP* macros skip over characters of a particular class and
 * leave cp at the position of the first character that doesn't match
 * that class. Correspondingly, SKIPTO* skips until it reaches a
 * character of a particular class.
 */

#define INIT()       { cp = yytext;} 
#define SETWDAY()    { cp++; \
                       tw.tw_wday= day_map[(cp[0] & 7) + (cp[1] & 4)]; \
                       tw.tw_flags &= ~TW_SDAY; tw.tw_flags |= TW_SEXP; \
                       SKIPA(); }
#define SETMON()     { cp++; \
                       tw.tw_mon = month_map[(cp[0] + cp[1]) & 0x1f]; \
  		       SKIPA(); }
#define SETMON_NUM() { tw.tw_mon = atoi(cp)-1; \
  		       SKIPD(); }
#define SETYEAR()    { tw.tw_year = atoi(cp); \
  		       SKIPD(); }
#define SETDAY()     { tw.tw_mday = atoi(cp); \
                       tw.tw_flags |= TW_YES; \
  		       SKIPD(); }
#define SETTIME()    { tw.tw_hour = atoi(cp); \
                       cp += 2; \
                       SKIPTOD(); \
                       tw.tw_min = atoi(cp); \
                       cp += 2; \
                       if(*cp == ':') { \
                          tw.tw_sec = atoi(++cp); SKIPD(); } }
#define SETZONE(x)   { tw.tw_zone = ((x)/100)*60+(x)%100; \
                       tw.tw_flags |= TW_SZEXP; \
                       SKIPD(); }
#define SETDST()     { tw.tw_flags |= TW_DST; }
#define SKIPD()      { while ( isdigit(*cp++) ) ; \
                       --cp; }
#define SKIPTOD()    { while ( !isdigit(*cp++) ) ; \
                       --cp; }
#define SKIPA()      { while ( isalpha(*cp++) ) ; \
                       --cp; }
#define SKIPTOA()    { while ( !isalpha(*cp++) ) ; \
                       --cp; }
#define SKIPSP()     { while ( isspace(*cp++) ) ; \
                       --cp; }
#define SKIPTOSP()   { while ( !isspace(*cp++) ) ; \
                       --cp; }
/* The year can either be 2 digits, or 4. However, after
Y2K, we found that some MUA were reporting the year 100, hence
the middle term here. yyterminate() resolves the actual
issues with 2-digit years.
*/

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 197 "dtimep.lex"


  /* This section begins the definition of dparsetime().
     Put here any local variable definitions and initializations */
  
  YY_BUFFER_STATE lexhandle;

  register char *cp;
  static struct tws tw; 

  memset(&tw,0,sizeof(struct tws));

  lexhandle = yy_scan_string(lexstr);



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 614 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 989 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 212 "dtimep.lex"
{
                                     INIT();
				     SETWDAY();
				     SKIPTOA();
				     SETMON();
				     SKIPTOD();
				     SETDAY();
				     SKIPTOD();
				     SETTIME();
				     SKIPTOD();
				     SETYEAR();
                                     }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 225 "dtimep.lex"
{
                                     INIT();
				     SETWDAY();
				     SKIPTOD();
				     SETDAY();
				     SKIPTOA();
				     SETMON();
				     SKIPTOD();
				     SETYEAR();
				     SKIPTOD();
				     SETTIME();
                                     }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 237 "dtimep.lex"
{
                                     INIT();
				     SETDAY();
				     SKIPTOA();
				     SETMON();
				     SKIPTOD();
				     SETYEAR();
				     SKIPTOD();
				     SETTIME();
                                     }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 247 "dtimep.lex"
{
                                     INIT();
				     SETWDAY();
				     SKIPTOA();
				     SETMON();
				     SKIPTOD();
				     SETDAY();
				     SKIPTOD();
				     SETYEAR();
				     SKIPTOD();
				     SETTIME();
                                     }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 259 "dtimep.lex"
{
                                     INIT();
				     SETWDAY();
				     SKIPTOA();
				     SETMON();
				     SKIPTOD();
				     SETDAY();
				     SKIPTOD();
				     SETYEAR();
                                     }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 269 "dtimep.lex"
{
                                     INIT();
				     SETMON();
				     SKIPTOD();
				     SETDAY();
				     SKIPTOD();
				     SETYEAR();
				     SKIPTOA();
				     SETWDAY();
                                     }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 279 "dtimep.lex"
{
                                     INIT();
				     SETMON();
				     SKIPTOD();
				     SETDAY();
				     SKIPTOD();
				     SETYEAR();
                                     }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 287 "dtimep.lex"
{
                                     INIT();
				     if(europeandate) {
				       /* DD/MM/YY */
				     SETDAY();
				     SKIPTOD();
				     SETMON_NUM();
				     } else {
				       /* MM/DD/YY */
				     SETMON_NUM();
				     SKIPTOD();
				     SETDAY();
				     }
				     SKIPTOD();
				     SETYEAR();
				     SKIPTOD();
				     SETTIME();
                                     }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 305 "dtimep.lex"
{
                                     INIT();
				     if(europeandate) {
				       /* DD/MM/YY */
				     SETDAY();
				     SKIPTOD();
				     SETMON_NUM();
				     } else {
				       /* MM/DD/YY */
				     SETMON_NUM();
				     SKIPTOD();
				     SETDAY();
				     }
				     SKIPTOD();
				     SETYEAR();
                                     }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 322 "dtimep.lex"

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 323 "dtimep.lex"
tw.tw_hour += 12;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 325 "dtimep.lex"
{
                                    INIT();
                                    SKIPTOD();
                                    SETZONE(atoi(cp));
                                    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 330 "dtimep.lex"
{
                                    INIT();
                                    SKIPTOD();
                                    SETZONE(-atoi(cp));
                                    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 335 "dtimep.lex"
INIT(); SETZONE(0);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 336 "dtimep.lex"
INIT(); SETZONE(0);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 337 "dtimep.lex"
INIT(); SETZONE(200);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 338 "dtimep.lex"
INIT(); SETDST(); SETZONE(2);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 339 "dtimep.lex"
INIT(); SETZONE(-500);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 340 "dtimep.lex"
INIT(); SETDST(); SETZONE(-500);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 341 "dtimep.lex"
INIT(); SETZONE(-600);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 342 "dtimep.lex"
INIT(); SETDST(); SETZONE(-600);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 343 "dtimep.lex"
INIT(); SETZONE(-700);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 344 "dtimep.lex"
INIT(); SETDST(); SETZONE(-700);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 345 "dtimep.lex"
INIT(); SETZONE(-800);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 346 "dtimep.lex"
INIT(); SETDST(); SETZONE(-800);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 347 "dtimep.lex"
INIT(); SETZONE(-330);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 348 "dtimep.lex"
INIT(); SETZONE(-400);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 349 "dtimep.lex"
INIT(); SETDST(); SETZONE(-400);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 350 "dtimep.lex"
INIT(); SETZONE(-900);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 351 "dtimep.lex"
INIT(); SETDST(); SETZONE(-900);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 352 "dtimep.lex"
INIT(); SETZONE(-1000);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 353 "dtimep.lex"
INIT(); SETDST(); SETZONE(-1000);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 354 "dtimep.lex"
INIT(); SETDST(); SETZONE(-100);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 355 "dtimep.lex"
{
                                       INIT();
                                       SETZONE(100*(('a'-1) - tolower(*cp)));
			            }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 359 "dtimep.lex"
{
                                       INIT();
                                       SETZONE(100*('a' - tolower(*cp)));
			            }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 363 "dtimep.lex"
{
                                       INIT();
                                       SETZONE(100*(tolower(*cp) - 'm'));
                                    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 367 "dtimep.lex"

	YY_BREAK
case 38:
YY_RULE_SETUP
#line 368 "dtimep.lex"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 614 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 614 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 613);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 368 "dtimep.lex"
