#!/bin/sh

set -e

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname "$0"`/../..
    MH_OBJ_DIR=`cd "$srcdir" && pwd`; export MH_OBJ_DIR
fi

. "$MH_OBJ_DIR/test/common.sh"

setup_test

mail="$MH_TEST_DIR/$$.mail"
expected="$MH_TEST_DIR/$$.expected"
actual="$MH_TEST_DIR/$$.actual"

cat >"$mail" <<\E
a:b
cd:ef
ghi:jkl
mnop:rstu
E
sed 's/.*://' "$mail" >"$expected"
f="`sed 's/:.*/}/; s/^/%{/' "$mail"`"
run_prog scan -forma "$f" -file "$mail" >"$actual" ||
exit 1
check "$expected" "$actual" expectfail

exit $failed
