#!/bin/sh
######################################################
#
# Test that whatnow's "ls" copes with directory names
# which have spaces and quotes in them (see bug #23319)
#
######################################################

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname $0`/../..
    MH_OBJ_DIR=`cd $srcdir && pwd`; export MH_OBJ_DIR
fi

. "$MH_OBJ_DIR/test/common.sh"

setup_test

set -e
SPDIR="$MH_TEST_DIR/foo's bar"
rm -rf "$SPDIR"
mkdir "$SPDIR"
cd "$SPDIR"
touch baz boz

expectederr=$MH_TEST_DIR/$$.expectederr
actualerr=$MH_TEST_DIR/$$.actualerr
expected=$MH_TEST_DIR/$$.expected
actual=$MH_TEST_DIR/$$.actual

cat > $expected <<EOF
baz
boz
EOF

cat > $expectederr <<EOF
EOF

# NB use of sort as the order of output of ls is not guaranteed
echo 'ls' | whatnow -noedit -prompt '' 2> "$actualerr" | sort > "$actual"

diff -u $expectederr $actualerr || exit 1
diff -u $expected $actual
