#!/bin/sh
#
# Tests to see if "forw -digest" works correctly.
#

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname "$0"`/../..
    MH_OBJ_DIR=`cd "$srcdir" && pwd`; export MH_OBJ_DIR
fi

. "$MH_OBJ_DIR/test/common.sh"

setup_test

expected="${MH_TEST_DIR}/$$.expected"
actual="${MH_TEST_DIR}/Mail/draft"
from="Mr Test User <test@user.com>"
to1="User One <userone@test.com>"
to2="User Two <usertwo@test.com>"
cc1="CC User One <ccuserone@test.com>"
cc2="CC User Two <ccusertwo@test.com>"
cc3="CC User Three <ccuserthree@test.com>"
cc4="CC User Four <ccuserfour@test.com>"
fcc1="+nosuchmailbox"
fcc2="+nosuchmailbox2"

cat > "$expected" <<EOF
From: ${from}
To: ${to1}, ${to2}
cc: ${cc1},
    ${cc2},
    ${cc3},
    ${cc4}
Fcc: ${fcc1}, ${fcc2}
Subject: foo
--------


EOF

forw -editor true -from "${from}" -to "${to1}" -to "${to2}" \
    -cc "${cc1}" -cc "${cc2}" -cc "${cc3}" -cc "${cc4}" -fcc "${fcc1}" \
    -fcc "${fcc2}" -width 60 -nowhatnowproc 1 \
    -digest digest-test +inbox 1-6 || exit 1

check "${expected}" "${actual}"

test "${failed:-0}" -eq 0 && rm "${form}"

exit $failed
