#!/bin/sh
#
# Test the basic behavior of post when configured with pipe delivery method.
#

set -e

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname "$0"`/../..
    MH_OBJ_DIR=`cd "$srcdir" && pwd`; export MH_OBJ_DIR
fi

. "${MH_OBJ_DIR}/test/common.sh"

setup_test
testname="${MH_TEST_DIR}/$$"

#### Force test of pipe regardless of configuration.
mts_pipe="${MHMTSCONF}-pipe"
sed -e 's/mts: *.*/mts: pipe/' "${MHMTSCONF}" >"$mts_pipe"
printf "%s\n" "sendmail: ${srcdir}/test/fakesendmail" >>"$mts_pipe"
MHMTSCONF="$mts_pipe"

test_pipe ()
{
  send -draft

  # fakesendmail drops the message and any cc's into this mbox.
  mbox="${MH_TEST_DIR}"/Mail/fakesendmail.mbox
  inc -silent -file "$mbox"
  rm -f "$mbox" "$mbox.map"

  n=1
  for expected in "$@"; do
    #
    # It's hard to calculate the exact Date: header post is going to
    # use, so we'll just use sed to remove the actual date so we can easily
    # compare it against our "correct" output.
    #
    sed -e 's/^Date:.*/Date:/' "`mhpath cur`" > "${testname}.actual$n"

    check "${testname}.actual$n" "$expected"

    if [ "`mhpath cur`" != "`mhpath last`" ]; then
      folder next >/dev/null
      arith_eval $n + 1; n=$arith_val
    fi
  done
}

#
# Basic test - Simple message, single user, single recipient.
# Dots are not stuffed because pipe invokes sendmail with -i.
#
cat > "${MH_TEST_DIR}/Mail/draft" <<EOF
From: Mr Nobody <nobody@example.com>
To: Somebody Else <somebody@example.com>
Subject: Test

This is a test
.
EOF

cat > "${testname}.expected" <<EOF
From: Mr Nobody <nobody@example.com>
To: Somebody Else <somebody@example.com>
Subject: Test
Date:

This is a test
.
EOF

test_pipe "${testname}.expected"


# check Bcc
cat > "${MH_TEST_DIR}/Mail/draft" <<EOF
From: Mr Nobody <nobody@example.com>
To: Somebody Else <somebody@example.com>
Bcc: Silent Partner <bcc@example.com>
Subject: Test

This is a test
.
EOF

cat > "${testname}.expected1" <<EOF
From: Mr Nobody <nobody@example.com>
To: Somebody Else <somebody@example.com>
Subject: Test
Date:

This is a test
.
EOF

cat > "${testname}.expected2" <<EOF
Date:
Subject: Test

------- Blind-Carbon-Copy

From: Mr Nobody <nobody@example.com>
To: Somebody Else <somebody@example.com>
Subject: Test
Date:

This is a test
.

------- End of Blind-Carbon-Copy
EOF

test_pipe "${testname}.expected1" "${testname}.expected2"


rm -f ${MHMTSCONF}

exit ${failed:-0}
