#!/bin/sh
######################################################
#
# Test the creation and removal of a folder.
#
######################################################

folder -create +testfolder > /dev/null
if [ ! -d "$MH_TEST_DIR/Mail/testfolder" ]; then
    exit 1
fi

rmf +testfolder > /dev/null
if [ -d "$MH_TEST_DIR/Mail/testfolder" ]; then
    # Test failed
    exit 1
fi
