#!/bin/csh -f
#
# Script to run rdist in order to update the Sun-3 filesservers
#
if (`hostname` == 'ics.uci.edu') then
  cd /usr/local/bin
  rdist -f /usr/src/bs/mh-6.6/rdist_update_usrlocal.sequent
  cd /usr/local/lib/mh
  rdist -f /usr/src/bs/mh-6.6/rdist_update_lib.sequent
  rdist -f /usr/src/bs/mh-6.6/rdist_update_others.sequent
else if (`hostname` == 'f.ics.uci.edu') then
  cd /usr/local
  rdist -f /usr/src/bs/mh-6.6/rdist_update_usrlocal.is68k
  cd /usr/local/lib/mh
  rdist -f /usr/src/bs/mh-6.6/rdist_update_lib.is68k
  rdist -f /usr/src/bs/mh-6.6/rdist_update_others.is68k
else
  cd /usr/local
  rdist -f /usr/src/bs/mh-6.6/rdist_update_usrlocal.`arch`
  cd /usr/local/lib/mh
  rdist -f /usr/src/bs/mh-6.6/rdist_update_lib.`arch`
  rdist -f /usr/src/bs/mh-6.6/rdist_update_others.`arch`
endif
