#!/bin/sh
######################################################
#
# Test the creation and removal of a folder.
#
######################################################

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname "$0"`/../..
    MH_OBJ_DIR=`cd "$srcdir" && pwd`; export MH_OBJ_DIR
fi

. "$MH_OBJ_DIR/test/common.sh"

setup_test

run_prog folder -create +testfolder > /dev/null
if [ -d "$MH_TEST_DIR/Mail/testfolder" ]; then
    :
else
    exit 1
fi

run_prog rmf +testfolder > /dev/null
if [ -d "$MH_TEST_DIR/Mail/testfolder" ]; then
    # Test failed
    exit 1
fi
