#!/bin/sh
######################################################
#
# Test the creation and removal of a folder.
#
######################################################

if [ -z "${MH_TEST_COMMON}" ]; then
    echo "MH_TEST_COMMON not set; try running via 'make check'"
fi

. ${MH_TEST_COMMON}

setup_test

folder -create +testfolder > /dev/null
if [ ! -d "$MH_TEST_DIR/Mail/testfolder" ]; then
    exit 1
fi

rmf +testfolder > /dev/null
if [ -d "$MH_TEST_DIR/Mail/testfolder" ]; then
    # Test failed
    exit 1
fi
