#! /bin/sh
#
# Configures and builds nmh.
# * This script must be invoked from an nmh source directory.
# * This script retrieves configuration from the first existing nmh
#   installation on your $PATH, if any.
# * Unless the -y option is provided, this script then interactively
#   walks you through confirmation of common configuration settings.
#
# Typical usage:
# The first time you invoke this script, use the -i option to install
# nmh in the specified location.  The script will walk you through the
# common nmh configuration settings.  The -v option will cause display
# of brief progress indicators.  Be sure to add the bin directory of
# the install location to your $PATH, if not already there.
# Subsequently, invoke this script with the -y option, to use the
# relevant configuration settings from the installed nmh without
# confirmation.
#
# Option summary:
#   First time use:
#     -i to install nmh
#     -v to display progress
#   Subsequent uses, assuming installed nmh bin directory is on $PATH:
#     -y to accept all configuration options without confirmation
#   Output control:
#     -l <logfile name>, default 'build_nmh.log'
#   Advanced/developer use:
#     -c to run 'make distcheck' instead of 'make check'
#     -d to build nmh with debug enabled
#     -s to use 'make superclean': requires recent autoconf and automake,
#        see docs/README.developers
#     -r to build rpm
#
# On Fedora, at least these rpms must be installed:
#   gdbm-devel
#   ncurses-devel
#   cyrus-sasl-devel, if using sasl
#   openssl-devel, if using TLS
#   autoconf and automake, with -s (see docs/README.developers for versions)
#   rpm-build, with -r


####
#### Interpret command arguments.
####
check=check
debug=0
install=0
logfile=build_nmh.log
build_rpm=0
superclean=0
verbose=0
yes=0
usage="usage: $0
  [-c to run 'make distcheck' instead of 'make check']
  [-d to build nmh with debug enabled]
  [-i to install nmh]
  [-l <logfile name>, default '$logfile']
  [-r to build rpm]
  [-s to use 'make superclean': requires recent autoconf and automake]
  [-v to display progress]
  [-y to accept all configuration options without confirmation]"

while getopts 'cdil:rsvy?' arg; do
  case $arg in
    c  ) check=distcheck ;;
    d  ) debug=1 ;;
    i  ) install=1 ;;
    l  ) logfile=$OPTARG ;;
    r  ) build_rpm=1 ;;
    s  ) superclean=1 ;;
    v  ) verbose=1 ;;
    y  ) yes=1 ;;
    '?') echo "$usage"; exit 0 ;;
  esac
done
shift `expr $OPTIND - 1`

#### No command line arguments are supported.
if [ $# -gt 0 ]; then
  echo "usage: $0"
  exit 1
fi

#### Check to see that we're in a nmh source directory.
if grep 'the authors of nmh' COPYRIGHT >/dev/null; then
  :
else
  echo "$0: not in nmh source directory"
  exit 1
fi

####
#### Set up configure options.  Handle options that can have embedded
#### spaces (currently just smtpservers) specially.
####

#### Here are the config options that we will try to detect, then
#### confirm, and finally set.
config_prefix=/usr/local/nmh
config_locking=
config_mts=smtp
config_smtpservers=localhost
config_sasl=n
config_tls=n
config_debug=n


#### Find location of a program.  Bourne shell just puts the name in
#### $0 if it's found from the PATH, so search that if necessary.
finddir() {
  case $1 in
    */*) dirname "$1" ;;
    *  ) IFS=:
         for d in $PATH; do
           [ -f "${d:=.}/$1"  -a  -x "$d/$1" ]  &&  printf %s "$d"  &&  break
         done ;;
  esac
}

#### Figure out whether or not to use -n with tail.
case `printf 'OK\n' | tail -n 1 2>&1` in
  OK) tail='tail -n ' ;;
  *)  tail='tail -' ;;
esac

if install-mh -check >/dev/null 2>&1; then
  # Determine config options from installed nmh.
  mhbin=`finddir install-mh`

  config_prefix=`cd $mhbin/.. && pwd`

  mtsconf=`mhparam etcdir`/mts.conf
  if [ -f "$mtsconf" ]; then
    mts_entry=`grep '^mts:' "$mtsconf"`
    if [ "$mts_entry" ]; then
      mts=`echo "$mts_entry" | sed -e 's/^mts: *//'`
      if [ "$mts"  -a  "$mts" != smtp ]; then
        config_mts="$mts"
      fi
    fi

    mtsconfservers=`grep '^servers:' "$mtsconf"`
    if [ "$mtsconfservers" ]; then
      servers=`echo "$mtsconfservers" | \
               sed -e 's/^servers: *//' -e 's/ /\\\ /g'`
      [ "$servers" ]  &&  config_smtpservers="$servers"
    fi
  fi

  if test -x "$mhbin/mhparam"; then
    if mhparam sasl >/dev/null; then
      case `$mhbin/mhparam sasl` in
        *sasl*) config_sasl=y ;;
      esac

      case `$mhbin/mhparam tls` in
        *tls*) config_tls=y ;;
      esac
    else
      tput smso
      echo "$0: SASL and TLS detection not supported with current nmh"
      [ $yes -eq 1 ]  &&  echo "will not configure either one in"
      tput rmso
    fi
  fi
fi

[ $debug -ge 1 ]  &&  config_debug=y

if [ $yes -eq 0 ]; then
  #### Confirm each config setting with user.
  printf 'Install prefix [%s]: ' $config_prefix
  read prefix
  [ "$prefix" ]  &&  config_prefix="$prefix"

  printf 'Locking type (dot|fcntl|flock|lockf) [determined by configure]: '
  read locking
  [ "$locking" ]  &&  config_locking="$locking"

  printf 'MTS (smtp|sendmail/smtp|sendmail/pipe) [%s]: ' $config_mts
  read mts
  [ "$mts" ]  &&  config_mts="$mts"

  if [ "$config_mts" = smtp ]; then
    printf 'SMTP server(s), space separated [%s]: ' $config_smtpservers
    read response
    servers=`echo $response | sed -e 's/ /\\\ /g'`
    [ "$servers" ]  &&  config_smtpservers="$servers"
  fi

  printf 'Cyrus SASL support [%s]: ' $config_sasl
  read response
  if [ "$response" = y  -o  "$response" = Y ]; then
    config_sasl=y
  elif [ "$response" = n  -o  "$response" = N ]; then
    config_sasl=n
  fi

  printf 'TLS support [%s]: ' $config_tls
  read response
  if [ "$response" = y  -o  "$response" = Y ]; then
    config_tls=y
  elif [ "$response" = n  -o  "$response" = N ]; then
    config_tls=n
  fi

  #### Don't confirm debug here:  obey the -d option to this script.
fi

smtpservers=
config_opts="--prefix=$config_prefix"

[ "$config_locking" ]  &&  \
  config_opts="$config_opts --with-locking=$config_locking"
[ "$config_mts"  -a  "$config_mts" != smtp ]  &&  \
  config_opts="$config_opts --with-mts=$config_mts"
[ "$config_smtpservers"  -a  "$config_smtpservers" != localhost ]  &&  \
  smtpservers="--with-smtpservers=$config_smtpservers"
[ "$config_sasl" = y ]  &&  \
  config_opts="$config_opts --with-cyrus-sasl"
[ "$config_tls" = y ]  &&  \
  config_opts="$config_opts --with-tls"
[ $config_debug = y ]  &&  \
  config_opts="$config_opts --enable-debug --enable-assert"


#### dotlocking, the usual default, requires chgrp and chmod of inc.
installpriv=
if [ $install -ge 1  -a  `id -u` -ne 0 ]; then
  if [ "$config_locking" = dot ]; then
    echo "$0: "'install requires chgrp and chmod 2755'
    echo 'so will sudo to install.  Terminate with Ctrl-C if unacceptable.'
    installpriv=sudo
  fi
fi


####
#### Clean up, and set up with autoconfig if necessary.
####
if [ -f Makefile ]; then
  [ $verbose -ge 1 ]  &&  echo cleaning . . .
  if [ $superclean -ge 1 ]; then
    make superclean >/dev/null
  else
    make distclean >/dev/null
  fi
fi

/bin/rm -f "$logfile"
if [ -f configure  -a  -f Makefile.in ]; then
  :
else
  [ $verbose -ge 1 ]  &&  echo autoconfiguring . . .
  ./autogen.sh >>"$logfile" 2>&1
fi


####
#### Build.
####
[ $verbose -ge 1 ]  &&  echo configuring . . .
echo ./configure $config_opts ${smtpservers:+"$smtpservers"} >>"$logfile" 2>&1
./configure $config_opts ${smtpservers:+"$smtpservers"} >>"$logfile" 2>&1
status=$?

if [ $status -eq 0 ]; then
  [ $verbose -ge 1 ]  &&  echo building . . .
  make >>"$logfile" 2>&1
  status=$?

  if [ $status -eq 0 ]; then
    if [ "$TESTS_SHELL"x = x ]; then
      #### Bonus:  use heirloom shell to test, if available, and if
      #### TESTS_SHELL hadn't already been set.
      heirloom_shell=/usr/lib/heirloom/5bin/sh
      if [ -x "$heirloom_shell" ]; then
        TESTS_SHELL="$heirloom_shell"; export TESTS_SHELL
      fi
   fi

    [ $verbose -ge 1 ]  &&  echo testing . . .
    checkoutput=`make $check AM_COLOR_TESTS=always 2>>"$logfile"`
    status=$?

    tests_summary=`echo "$checkoutput" | grep tests`
    #### If multiple tests not run, that line will be caught by the
    #### "grep tests" above.
    test_not_run=`echo "$checkoutput" | grep 'test was not run'`
    fails=`echo "$checkoutput" | grep FAIL`
    if [ "$tests_summary" ]; then
      echo '===================' >>"$logfile"
      [ "$test_not_run" ]  &&  echo "$test_not_run" >>"$logfile"
      [ "$fails" ]  &&  echo "$fails" >>"$logfile"
      echo "$tests_summary" >>"$logfile"
      echo '===================' >>"$logfile"
      [ "$check" = distcheck ]  &&  \
        echo "$checkoutput" | ${tail}4 >>"$logfile"
    fi

    if [ $status -eq 0 ]; then
      if [ $install -ge 1 ]; then
        [ $verbose -ge 1 ]  &&  echo installing . . .
        ($installpriv make install) >/dev/null 2>>"$logfile"
        status=$?
      fi

      if [ $status -eq 0  -a  $build_rpm -ge 1 ]; then
        [ $verbose -ge 1 ]  &&  echo building rpm . . .
        make rpm >/dev/null 2>>"$logfile"
        status=$?
      fi
    fi
  fi
fi

grep Error "$logfile"
grep warn "$logfile"

if [ $status -eq 0 ]; then
  [ $verbose -ge 1 ]  &&  echo build completed successfully
else
  echo build failed!
  echo build log is in "$logfile"
fi

exit $status
