#!/bin/sh
######################################################
#
# Test bogus headers (no blank line before body).
#
######################################################

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname "$0"`/../..
    MH_OBJ_DIR=`cd "$srcdir" && pwd`; export MH_OBJ_DIR
fi

. "$MH_OBJ_DIR/test/common.sh"

setup_test

expected=$MH_TEST_DIR/$$.expected
actual=$MH_TEST_DIR/$$.actual

# Write message with bogus header field (missing blank line, really).
msgfile=`mhpath new`
msgnum=`basename $msgfile`
cat > $msgfile <<EOF
Date: Sun, 18 Dec 2005 00:52:39 +0100
From: foo@example.edu
To: bar@example.edu
Subject: test
This is a multi-part message in MIME format.

I am a stupid spammer.
EOF

# check scan
cat > $expected <<EOF
  11  12/18 foo@example.edu    test<<This is a multi-part message in MIME forma
EOF
scan -width 80 $msgnum > $actual 2>&1
check $expected $actual

# check show (mhl)
cat > $expected <<EOF
(Message inbox:11)

Date:    Sun, 18 Dec 2005 00:52:39 +0100
To:      bar@example.edu
From:    foo@example.edu
Subject: test


This is a multi-part message in MIME format.

I am a stupid spammer.
EOF
show $msgnum > $actual 2>&1
check $expected $actual

# check mhshow
cat > $expected <<EOF
Date:    Sun, 18 Dec 2005 00:52:39 +0100
To:      bar@example.edu
From:    foo@example.edu
Subject: test


part       text/plain                  70

This is a multi-part message in MIME format.

I am a stupid spammer.
EOF
mhshow -nopause $msgnum > $actual 2>&1
check $expected $actual

exit $failed
