#!/bin/sh
######################################################
#
# Test the creation of RFC 2231 encoded parameters
#
######################################################

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname "$0"`/../..
    MH_OBJ_DIR=`cd "$srcdir" && pwd`; export MH_OBJ_DIR
fi

. "$MH_OBJ_DIR/test/common.sh"

setup_test

LC_ALL=en_US.UTF-8; export LC_ALL

draft="$MH_TEST_DIR/$$.draft"
expected="$MH_TEST_DIR/$$.expected"

#
# Try out a draft with some 8-bit encoded parameters
#

cat > "$draft" <<EOF
To: Mr Test <mrtest@example.com>
cc:
Fcc: +outbox
------
This is a test message
#image/jpeg {attachment; filename="tïny.jpg"} ${srcdir}/test/mhbuild/tiny.jpg
EOF

run_prog mhbuild "$draft"

cat > "$expected" <<EOF
To: Mr Test <mrtest@example.com>
cc:
Fcc: +outbox
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----- =_aaaaaaaaaa0"

------- =_aaaaaaaaaa0
Content-Type: text/plain; charset="us-ascii"

This is a test message

------- =_aaaaaaaaaa0
Content-Type: image/jpeg
Content-Disposition: attachment; filename*=UTF-8''t%C3%AFny.jpg
Content-Transfer-Encoding: base64

/9g=

------- =_aaaaaaaaaa0--
EOF

check "$draft" "$expected"

#
# Try out a draft with some long parameters
#

cat > "$draft" <<EOF
To: Mr Test <mrtest@example.com>
cc:
Fcc: +outbox
------
This is a test message
#image/jpeg {attachment; filename="This is an example of a rather long filename that is longer than would fit on a normal line.jpg"} \
${srcdir}/test/mhbuild/tiny.jpg
EOF

run_prog mhbuild "$draft"

cat > "$expected" <<EOF
To: Mr Test <mrtest@example.com>
cc:
Fcc: +outbox
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----- =_aaaaaaaaaa0"

------- =_aaaaaaaaaa0
Content-Type: text/plain; charset="us-ascii"

This is a test message

------- =_aaaaaaaaaa0
Content-Type: image/jpeg
Content-Disposition: attachment;
	filename*0="This is an example of a rather long filename that is lo";
	filename*1="nger than would fit on a normal line.jpg"
Content-Transfer-Encoding: base64

/9g=

------- =_aaaaaaaaaa0--
EOF

check "$draft" "$expected"

#
# Try out both!
#

cat > "$draft" <<EOF
To: Mr Test <mrtest@example.com>
cc:
Fcc: +outbox
------
This is a test message
#image/jpeg {attachment; filename="This is an ëxample of a rather long filename that is longer than would fit on a normal line.jpg"} \
${srcdir}/test/mhbuild/tiny.jpg
EOF

run_prog mhbuild "$draft"

cat > "$expected" <<EOF
To: Mr Test <mrtest@example.com>
cc:
Fcc: +outbox
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----- =_aaaaaaaaaa0"

------- =_aaaaaaaaaa0
Content-Type: text/plain; charset="us-ascii"

This is a test message

------- =_aaaaaaaaaa0
Content-Type: image/jpeg
Content-Disposition: attachment;
	filename*0*=UTF-8''This%20is%20an%20%C3%ABxample%20of%20a%20rather;
	filename*1=" long filename that is longer than would fit on a norma";
	filename*2="l line.jpg"
Content-Transfer-Encoding: base64

/9g=

------- =_aaaaaaaaaa0--
EOF

check "$draft" "$expected"

exit ${failed:-0}
