#!/bin/sh
######################################################
#
# Test the use of the Attach: header
#
######################################################

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname "$0"`/../..
    MH_OBJ_DIR=`cd "$srcdir" && pwd`; export MH_OBJ_DIR
fi

. "$MH_OBJ_DIR/test/common.sh"

setup_test

draft="$MH_TEST_DIR/$$.draft"
expected="$MH_TEST_DIR/$$.expected"
actual="$MH_TEST_DIR/$$.actual"

#
# Test out a simple draft
#

cat > "$draft" <<EOF
To: Mr Test <mrtest@example.com>
cc:
Fcc: +outbox
Attach: ${srcdir}/test/mhbuild/tiny.jpg
------
Test
EOF

mhbuild "$draft"

cat $draft

exit $failed
