#!/bin/sh
#
# Test of various (well, start with one) function escapes.

set -e

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname "$0"`/../..
    MH_OBJ_DIR=`cd "$srcdir" && pwd`; export MH_OBJ_DIR
fi

. "$MH_OBJ_DIR/test/common.sh"

setup_test
expected="$MH_TEST_DIR/test-functions$$.expected"
actual="$MH_TEST_DIR/test-functions$$.actual"

# check sday when day of week is specified
printf '1\n' >"$expected"
fmttest -raw -format '%(sday{text})' 'Fri Sep 12 20:02 2014' >"$actual"
check "$expected" "$actual"

# check sday when day of week is not specified
printf '0\n' >"$expected"
fmttest -raw -format '%(sday{text})' 'Sep 12 20:02 2014' >"$actual"
check "$expected" "$actual"

# check negative number, without padding
printf '%s\n' ' -42' >"$expected"
fmttest -raw -format '%4(minus -42)' 0 >"$actual"
check "$expected" "$actual"

# check negative number, with padding
# Output was "0-42" with nmh 1.6 and earlier.
printf '%s\n' -042 >"$expected"
fmttest -raw -format '%04(minus -42)' 0 >"$actual"
check "$expected" "$actual"


exit $failed
