#!/bin/sh
#
# Test that the %(mymbox) function correctly determines whether or not
# a particular email address is "mine" or not
#

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname $0`/../..
    MH_OBJ_DIR=`cd $srcdir && pwd`; export MH_OBJ_DIR
fi

. "$MH_OBJ_DIR/test/common.sh"

setup_test

runtest()
{
	testoutput=$(${MH_LIB_DIR}/ap -format "%(mymbox{text})" "$1")

	if [ -z "${testoutput}" ]; then
		echo "Test program did not return anything for $3"
		exit 1
	fi

	if [ "${testoutput}" -ne $2 ]; then
		echo "Did not get expected output for $3"
		exit 1
	fi
}

user="$(id -un)"
host="$(hostname)"

runtest "${user}" 1 "Basic user test"
runtest "${user}@${host}" 1 "Basic user@host test"
runtest "nosuchuser@nosuchhost.blah" 0 "Basic non-matching test"

myname="Random User <random@user.something.com>"

echo "Local-Mailbox: ${myname}" >> ${MH}

runtest "${myname}" 1 "Local-Mailbox test"
runtest "${user}@${host}" 0 "Local-mailbox overriding user@host test"

exit 0
