#!/bin/sh
#
# Test that the %(myhost) function returns the local hostname and
# the localname entry out of the mts configuration file.
#

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname "$0"`/../..
    MH_OBJ_DIR=`cd "$srcdir" && pwd`; export MH_OBJ_DIR
fi

. "$MH_OBJ_DIR/test/common.sh"

setup_test

start_test 'local hostname test'
set +e
host=`${MH_OBJ_DIR}/test/getcanon`
set -e
myhost=`${MH_LIBEXEC_DIR}/ap -format '%(myhost)' ignore 2>&1`
if [ "$myhost" != "$host" ]; then
   echo "$0: myhost reports $myhost but canonical hostname is $host"
fi

start_test 'mts.conf localname test'
cp ${MHMTSCONF} ${MH_TEST_DIR}/Mail/mts.conf || exit 1
MHMTSCONF="${MH_TEST_DIR}/Mail/mts.conf"

echo "localname: some.random.name" >> ${MHMTSCONF}

run_test "${MH_LIBEXEC_DIR}/ap -format %(myhost) ignore" "some.random.name"


finish_test
exit $failed
