#!/bin/sh
#
# Test that the unquote function works properly.
#

if test -z "${MH_OBJ_DIR}"; then
    srcdir=`dirname "$0"`/../..
    MH_OBJ_DIR=`cd "$srcdir" && pwd`; export MH_OBJ_DIR
fi

. "$MH_OBJ_DIR/test/common.sh"

setup_test

#
# Test various unquoting scenarios
#

name='"Mr. Foo Bar"'

run_test "fmttest -raw -format %(unquote{text}) $name" \
		'Mr. Foo Bar'

exit ${failed:-0}
